services:
  - type: web
    name: tiny-outings
    runtime: static
    buildCommand: npm install && npm run review:build && npm run render:download
    staticPublishPath: render-mobile
    routes:
      - type: rewrite
        source: /review/*
        destination: /review/index.html
    headers:
      - path: /
        name: Cache-Control
        value: no-cache, no-store, must-revalidate
      - path: /downloads/*
        name: Cache-Control
        value: no-cache, no-store, must-revalidate
      - path: /review/index.html
        name: Cache-Control
        value: no-cache, no-store, must-revalidate
      - path: /review/assets/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
