-- Generated by scripts/enrich-activity-images.js

-- Generated at 2026-07-23T14:51:52.515Z

-- Organiser images are preferred; listing images are the fallback.

-- Cards without a usable website image render the in-app category illustration.

-- Always serve images securely in the HTTPS mobile app.
update public.activities
set
  image_url = regexp_replace(image_url, '^http://', 'https://', 'i'),
  updated_at = now()
where image_url ~* '^http://';

-- Remove interface assets, tracking pixels, and other non-activity images.
-- The client displays a category illustration whenever image_url is null.
update public.activities
set
  image_url = null,
  image_source_url = null,
  updated_at = now()
where coalesce(image_url, '') ~* '(favicon|icon|logo|wordmark|sprite|avatar|placeholder|apple-touch|/flags/|site-flag|country-selector|language-selector|facebook[.]com/tr|facebook[.]net/tr|doubleclick|google-analytics|tracking-pixel|/pixel[.]|pixel[.]gif|[.]svg(?:[?#]|$)|google-play|google_play|app-store|app_store|download-button|cookie|consent|newsletter|payment|checkout)';

-- Applies audited website images and clears legacy Google Places photo values.

with image_updates (
  activity_id,
  google_place_id,
  google_place_uri,
  google_photo_url,
  google_rating,
  google_user_rating_count,
  image_url,
  image_source_url
) as (
  values
    ('446f3be0-6b5b-43c3-9e04-dd8678efa12b'::uuid, 'ChIJ7_PV980bdkgROekbwOVWVfo'::text, 'https://maps.google.com/?cid=18038419427272943929&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA'::text, null::text, 4.4::numeric, 3309::integer, 'https://applications-media.feverup.com/image/upload/f_auto,w_720,h_720/fever2/plan/photo/44786700-f5bd-11ef-8c72-a6d2952182ea'::text, 'https://feverup.com/m/309703'::text),
    ('66775102-4425-4aab-9ead-bb8500bc8620'::uuid, 'ChIJPVPe5jIbdkgRUSM8IVdz1pw'::text, 'https://maps.google.com/?cid=11301347132989776721&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA'::text, null::text, 4.3::numeric, 114::integer, 'https://applications-media.feverup.com/image/upload/f_auto,w_720,h_720/fever2/plan/photo/2e95f480-1f96-11ec-9dfb-d682130ea0e7.jpg'::text, 'https://feverup.com/m/103715'::text),
    ('65c60e2e-81e0-4c47-8a34-bc9f56cc457a'::uuid, 'ChIJQzRbYMUNdkgRfvuRYk-Rb9E'::text, 'https://maps.google.com/?cid=15091440646483999614&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA'::text, null::text, 4.7::numeric, 53758::integer, 'https://applications-media.feverup.com/image/upload/f_auto,w_720,h_720/fever2/plan/photo/c98df76a-4978-11f1-9e72-9a1ffdbd89fc.jpg'::text, 'https://feverup.com/m/631869'::text),
    ('70fca1eb-fcae-4b53-8521-e354ad4b4e05'::uuid, 'ChIJC9pWSLVBdkgRMA5Q9eG6egM'::text, 'https://maps.google.com/?cid=250718208918556208&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA'::text, null::text, 4.8::numeric, 102907::integer, 'https://applications-media.feverup.com/image/upload/f_auto,w_720,h_720/fever2/plan/photo/8291d96e-5149-11ee-8e81-a2654b591637'::text, 'https://feverup.com/m/139631'::text),
    ('654cf41d-f958-4427-bb5b-4dfc51803fa2'::uuid, 'ChIJqfua7FhzdkgRqSRaMoloxR0'::text, 'https://maps.google.com/?cid=2145235735976486057&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA'::text, null::text, 4.4::numeric, 2377::integer, 'https://applications-media.feverup.com/image/upload/f_auto,w_720,h_720/fever2/plan/photo/2e5af690-7acd-11f1-80a4-f2a1e8d39de5.png'::text, 'https://feverup.com/m/127412'::text),
    ('84cb8a17-4670-48ac-969e-d7a9297db3bc'::uuid, 'ChIJCfbtYpmp2EcRxO3NuYJIy5U'::text, 'https://maps.google.com/?cid=10793800658223754692&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA'::text, null::text, 4.9::numeric, 148::integer, 'https://applications-media.feverup.com/image/upload/f_auto,w_720,h_720/fever2/plan/photo/60a8017c-76bf-11f1-9fc1-062627165393.png'::text, 'https://feverup.com/m/628172'::text),
    ('dfeb1dc6-96ce-45b4-a28f-7803bb1b10c2'::uuid, 'ChIJ059kIs0EdkgRAbuyqaAavxU'::text, 'https://maps.google.com/?cid=1567000472692374273&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA'::text, null::text, 4.7::numeric, 6055::integer, 'https://applications-media.feverup.com/image/upload/f_auto,w_720,h_720/fever2/plan/photo/51ed64d6-ec17-11ee-bb83-b262fb5b0e8a.jpg'::text, 'https://feverup.com/m/122449'::text),
    ('cb16cea2-ba1f-4e54-97d3-825eb514a324'::uuid, 'ChIJ73KKU_AFdkgRFpRPAUnpw-M'::text, 'https://maps.google.com/?cid=16412217966832096278&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA'::text, null::text, 4.9::numeric, 12::integer, 'https://applications-media.feverup.com/image/upload/f_auto,w_720,h_720/fever2/plan/photo/3cc70810-1342-11f1-aea0-ee24abf6c566.jpg'::text, 'https://feverup.com/m/674657'::text),
    ('4ed33de4-93b9-4bfc-bbae-77ee0dd9de7e'::uuid, null::text, null::text, null::text, null::numeric, null::integer, 'https://applications-media.feverup.com/image/upload/f_auto,w_720,h_720/fever2/plan/photo/668c51f8-4891-11f1-969b-daa9519aa28e.png'::text, 'https://feverup.com/m/602434'::text),
    ('f9b22eb5-1c66-47d2-b937-8d02eea4b99b'::uuid, 'ChIJQzfybmYFdkgR1tFou0zyzYQ'::text, 'https://maps.google.com/?cid=9569571194607817174&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA'::text, null::text, 4.3::numeric, 4935::integer, 'https://applications-media.feverup.com/image/upload/f_auto,w_720,h_720/fever2/plan/photo/762a31c4-058b-11f0-9995-2a2765d93322.jpg'::text, 'https://feverup.com/m/176858'::text),
    ('d2006359-f64f-4758-ba34-b028a196735a'::uuid, 'ChIJeYT4GswEdkgRQFOsZ6aftsM'::text, 'https://maps.google.com/?cid=14102634820210021184&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA'::text, null::text, 4.4::numeric, 1718::integer, 'https://applications-media.feverup.com/image/upload/f_auto,w_720,h_720/fever2/plan/photo/63043128-2833-11f1-9390-e604dc7043ca.png'::text, 'https://feverup.com/m/596488'::text),
    ('daa8db89-c405-4371-82e8-e32e962dffc2'::uuid, 'ChIJeYT4GswEdkgRQFOsZ6aftsM'::text, 'https://maps.google.com/?cid=14102634820210021184&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA'::text, null::text, 4.4::numeric, 1718::integer, 'https://applications-media.feverup.com/image/upload/f_auto,w_720,h_720/fever2/plan/photo/f90a7d20-4891-11f1-a1cf-7a3e12657bc4.png'::text, 'https://feverup.com/m/599709'::text),
    ('5f606e5d-e185-487b-84a1-c83dd3eb302a'::uuid, 'ChIJeYT4GswEdkgRQFOsZ6aftsM'::text, 'https://maps.google.com/?cid=14102634820210021184&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA'::text, null::text, 4.4::numeric, 1718::integer, 'https://applications-media.feverup.com/image/upload/f_auto,w_720,h_720/fever2/plan/photo/02ede6a2-4891-11f1-858d-f6135ba131ed.png'::text, 'https://feverup.com/m/599704'::text),
    ('56b69885-e01b-4e1e-ac59-32e4f9464c15'::uuid, 'ChIJeYT4GswEdkgRQFOsZ6aftsM'::text, 'https://maps.google.com/?cid=14102634820210021184&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA'::text, null::text, 4.4::numeric, 1718::integer, 'https://applications-media.feverup.com/image/upload/f_auto,w_720,h_720/fever2/plan/photo/93116c22-4891-11f1-9781-ee6728a6aa38.png'::text, 'https://feverup.com/m/599365'::text),
    ('ae5b8473-4cde-40ec-b7b5-d30fcda167c1'::uuid, 'ChIJeYT4GswEdkgRQFOsZ6aftsM'::text, 'https://maps.google.com/?cid=14102634820210021184&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA'::text, null::text, 4.4::numeric, 1718::integer, 'https://applications-media.feverup.com/image/upload/f_auto,w_720,h_720/fever2/plan/photo/d200cffe-4891-11f1-bbab-7e064463a3c7.png'::text, 'https://feverup.com/m/599654'::text),
    ('9c3dec08-7b10-4694-b4fe-ff21b26b6aad'::uuid, 'ChIJ1WE10xoRdkgRHUIUP3OVu70'::text, 'https://maps.google.com/?cid=13671685416025342493&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA'::text, null::text, 4.4::numeric, 6768::integer, 'https://applications-media.feverup.com/image/upload/f_auto,w_720,h_720/fever2/plan/photo/0a7dd430-1e35-11f1-8a21-fac17089a9ac.jpg'::text, 'https://feverup.com/m/593901'::text),
    ('0d23ab00-ff4b-4a14-9f4f-635e2b472083'::uuid, 'ChIJcXx0Uoms2EcR8Be43HHdy2U'::text, 'https://maps.google.com/?cid=7335199899207079920&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA'::text, null::text, 4.7::numeric, 21517::integer, 'https://applications-media.feverup.com/image/upload/f_auto,w_720,h_720/fever2/plan/photo/efd988da-ec19-11ee-a983-0eaae6dd41d5.jpg'::text, 'https://feverup.com/m/125940'::text),
    ('2b2dca17-6b73-47c6-9582-183c2008b7d1'::uuid, 'ChIJkUcf6v4PdkgRIN0LQBjlSqs'::text, 'https://maps.google.com/?cid=12342929621078760736&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA'::text, null::text, 4.5::numeric, 2054::integer, 'https://museumofbrands.com/wp-content/uploads/2023/07/Time_Tunnel_Thumbnail_Back.jpg'::text, 'https://museumofbrands.com/'::text),
    ('d0d2cb34-ea0f-4b8b-8875-108e2e823b5a'::uuid, 'ChIJ89vMydEEdkgRODy6nj-F_rk'::text, 'https://maps.google.com/?cid=13402296049393613880&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA'::text, null::text, 4.1::numeric, 3242::integer, 'https://applications-media.feverup.com/image/upload/f_auto,w_720,h_720/fever2/plan/photo/cb3b9294-aa9d-11ec-8342-76caf20dc8e2'::text, 'https://feverup.com/m/112218'::text),
    ('be6cc36d-dda5-40b8-8c60-991850d5b945'::uuid, 'ChIJV_iXMtcadkgRqBI84CY_crE'::text, 'https://maps.google.com/?cid=12786351728261599912&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA'::text, null::text, 4.3::numeric, 36159::integer, 'https://applications-media.feverup.com/image/upload/f_auto,w_720,h_720/fever2/plan/photo/c46b33c4-f624-11ed-8f61-9a2e048935ba'::text, 'https://feverup.com/m/130775'::text)
)
update public.activities as activities
set
  google_place_id = coalesce(image_updates.google_place_id, activities.google_place_id),
  google_place_uri = coalesce(image_updates.google_place_uri, activities.google_place_uri),
  google_photo_url = null,
  google_rating = coalesce(image_updates.google_rating, activities.google_rating),
  google_user_rating_count = coalesce(image_updates.google_user_rating_count, activities.google_user_rating_count),
  image_url = image_updates.image_url,
  image_source_url = image_updates.image_source_url,
  updated_at = now()
from image_updates
where activities.activity_id = image_updates.activity_id;

