-- Generated by scripts/archive-expired-activities.js
-- Archive only records with an explicit end date in the past. Historical rows
-- remain in PostgreSQL and can be restored if their source publishes new dates.

with expired as (
  select activity_id
  from public.activities
  where public_listing_status = 'published'
    and (
      activity_date < current_date
      or availability_end_date < current_date
      or (
        availability_type in ('one_off', 'specific_dates')
        and coalesce((select max(day) from unnest(available_dates) as day), activity_date) < current_date
      )
    )
)
update public.activities as activity
set public_listing_status = 'archived', updated_at = now()
from expired
where activity.activity_id = expired.activity_id;
