-- Generated by scripts/enrich-activity-images.js

-- Generated at 2026-07-12T20:50:54.683Z

-- Applies Google Places image metadata first, with website image fallbacks.

with image_updates (
  activity_id,
  google_place_id,
  google_place_uri,
  google_photo_url,
  google_rating,
  google_user_rating_count,
  image_url,
  image_source_url
) as (
  values
    ('b7e2c8fa-8337-466e-86b4-03fdd5ee1975'::uuid, 'ChIJ81Qi5H0bdkgRy25gEqfbgxk'::text, 'https://maps.google.com/?cid=1838554583511625419&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA'::text, 'https://lh3.googleusercontent.com/place-photos/AG9NLjDLOzj3b-dtVcvIS98wnfTh3j8RoA8Qs8_lQ3e61kZ-KIFg9ZiBGL7foHwdOj6SvyHL_iZ68tB2XPz7vsE4gFScHJzA3nk-2AgMUVxIOH8t-5S91ewlwearih-MTq9M3onbRL3UrMfvNbgM4Q=s4800-w1200'::text, 4.6::numeric, 253::integer, 'https://lh3.googleusercontent.com/place-photos/AG9NLjDLOzj3b-dtVcvIS98wnfTh3j8RoA8Qs8_lQ3e61kZ-KIFg9ZiBGL7foHwdOj6SvyHL_iZ68tB2XPz7vsE4gFScHJzA3nk-2AgMUVxIOH8t-5S91ewlwearih-MTq9M3onbRL3UrMfvNbgM4Q=s4800-w1200'::text, 'https://maps.google.com/?cid=1838554583511625419&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA'::text),
    ('c2f1194c-53f1-48aa-ae35-3226aa9f0348'::uuid, 'ChIJj3TaVACn2EcR8y6XgUvhdXM'::text, 'https://maps.google.com/?cid=8319803601049825011&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA'::text, null::text, null::numeric, 0::integer, null::text, null::text),
    ('e3dbd48b-96b9-4699-a7e9-7f7246facd01'::uuid, 'ChIJn0oedQAddkgRwS7nhjyKiUU'::text, 'https://maps.google.com/?cid=5010688052992356033&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA'::text, null::text, 5::numeric, 1::integer, null::text, null::text),
    ('acf32363-088d-42bc-987f-31b327905e21'::uuid, 'ChIJ8b8qpHyn2EcR0kXUGl8SwVQ'::text, 'https://maps.google.com/?cid=6107182769372415442&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA'::text, null::text, null::numeric, 0::integer, null::text, null::text),
    ('f0cb5f2d-293b-49fa-856a-1de0aef71ed6'::uuid, 'ChIJMVZq8igddkgRt2WE9r_rkLc'::text, 'https://maps.google.com/?cid=13227331315294299575&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA'::text, null::text, 3::numeric, 2::integer, null::text, null::text),
    ('ba768bf4-c7e6-4571-8616-ab989a4ac1f3'::uuid, 'ChIJ7TlnFnqn2EcRYkeuuhMkPF8'::text, 'https://maps.google.com/?cid=6862399599360755554&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA'::text, null::text, 5::numeric, 2::integer, 'https://www.newham.gov.uk/site/dist/images/opengraph/opengraph.jpg?1.23.1'::text, 'https://www.newham.gov.uk/homepage/126/find-your-local-park'::text),
    ('4065fea1-5c39-46d1-923e-690f482b192e'::uuid, 'ChIJ2VTLQQCn2EcR72DfmCCxsrU'::text, 'https://maps.google.com/?cid=13092721820281299183&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA'::text, null::text, null::numeric, 0::integer, null::text, null::text),
    ('60b2feb5-8da1-4079-b1f0-8f23f677170b'::uuid, 'ChIJT6yBSQCn2EcRpLD9FHpLKGg'::text, 'https://maps.google.com/?cid=7505331766723195044&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA'::text, null::text, null::numeric, 0::integer, null::text, null::text),
    ('6f6eaf2f-5e06-4898-89ce-10fbf6c95d51'::uuid, 'ChIJEyK1AgAddkgRTQcfCPWQBfI'::text, 'https://maps.google.com/?cid=17439504514139752269&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA'::text, null::text, 5::numeric, 1::integer, null::text, null::text),
    ('53f45429-c63f-42b8-9879-f4785befbfab'::uuid, 'ChIJ_X9cDQCn2EcR0rP8YBBZ28o'::text, 'https://maps.google.com/?cid=14617374942442599378&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA'::text, null::text, null::numeric, 0::integer, null::text, null::text),
    ('e413250b-76f1-476d-abb4-eb9fbbf6d842'::uuid, 'ChIJ21zKEAAddkgRY27tDcerOwA'::text, 'https://maps.google.com/?cid=16795895046434403&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA'::text, null::text, 4::numeric, 1::integer, null::text, null::text),
    ('ba7b2977-6460-46da-b3a4-dbab2532a3bd'::uuid, 'ChIJ175mcwAddkgRo6o6DZu4t2c'::text, 'https://maps.google.com/?cid=7473645082726017699&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA'::text, null::text, null::numeric, 0::integer, null::text, null::text),
    ('9afec450-b0a0-4399-a9e8-0a12d8473f91'::uuid, 'ChIJj1ouOwAddkgR6lUnAby46ag'::text, 'https://maps.google.com/?cid=12171462585558193642&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA'::text, null::text, 5::numeric, 1::integer, null::text, null::text),
    ('6563ac02-67f8-4447-ba09-64046ce71dde'::uuid, 'ChIJwZc_cgAddkgRKU1XdI2RNCI'::text, 'https://maps.google.com/?cid=2464754932806798633&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA'::text, null::text, 5::numeric, 1::integer, null::text, null::text)
)
update public.activities as activities
set
  google_place_id = coalesce(image_updates.google_place_id, activities.google_place_id),
  google_place_uri = coalesce(image_updates.google_place_uri, activities.google_place_uri),
  google_photo_url = coalesce(image_updates.google_photo_url, activities.google_photo_url),
  google_rating = coalesce(image_updates.google_rating, activities.google_rating),
  google_user_rating_count = coalesce(image_updates.google_user_rating_count, activities.google_user_rating_count),
  image_url = coalesce(image_updates.image_url, activities.image_url),
  image_source_url = coalesce(image_updates.image_source_url, activities.image_source_url),
  updated_at = now()
from image_updates
where activities.activity_id = image_updates.activity_id;

