insert into public.activities (
  activity_name,
  address,
  postcode,
  lat,
  long,
  category,
  start_time,
  end_time,
  google_link,
  website,
  child_friendly_score,
  app_rating,
  number_of_reviews,
  age_suitability,
  borough,
  days_of_week,
  recurrence_rule,
  schedule_notes,
  description,
  cost,
  booking_required,
  source_name,
  source_url
)
values
(
  'Stay and play at Barclay Primary School, Leyton',
  'Barclay Primary School, 155 Canterbury Road, London E10 6EJ',
  'E10 6EJ',
  51.575756,
  -0.000933,
  'baby stay and play',
  '09:15',
  '10:15',
  'https://www.google.com/maps/search/?api=1&query=Barclay%20Primary%20School%20155%20Canterbury%20Road%20London%20E10%206EJ',
  'https://www.walthamforest.gov.uk/events/stay-and-play-barclay-primary-school-leyton',
  null,
  null,
  0,
  'Birth to 4 years',
  'Waltham Forest',
  array['Thursday'],
  'FREQ=WEEKLY;BYDAY=TH',
  'Best Start in Life weekly session, term time only. Event listing observed for Thursday 9 July 2026.',
  'Creative stay-and-play session with toys, child social time, and space for parents and carers to meet.',
  'GBP 1 per child',
  false,
  'London Borough of Waltham Forest events',
  'https://www.walthamforest.gov.uk/events/stay-and-play-barclay-primary-school-leyton'
),
(
  'Play and learn for under-2s at Best Start Family Hub: Walthamstow',
  'Walthamstow Family Hub, 313 Billet Road, London E17 5PX',
  'E17 5PX',
  51.597912,
  -0.040839,
  'baby stay and play',
  '09:30',
  '11:00',
  'https://www.google.com/maps/search/?api=1&query=Walthamstow%20Family%20Hub%20313%20Billet%20Road%20E17%205PX',
  'https://www.walthamforest.gov.uk/events/play-and-learn-under-2s-best-start-family-hub-walthamstow',
  null,
  null,
  0,
  'Under 2s',
  'Waltham Forest',
  array['Thursday'],
  'FREQ=WEEKLY;BYDAY=TH',
  'Best Start in Life weekly session, term time only. No booking required according to the source page.',
  'Interactive early-years play session focused on learning at home, routines, language, movement, and social connection.',
  'Free',
  false,
  'London Borough of Waltham Forest events',
  'https://www.walthamforest.gov.uk/events/play-and-learn-under-2s-best-start-family-hub-walthamstow'
),
(
  'Stay and Play at Chingford Library, Thursday',
  'Chingford Library, Chingford, London E4 7EN',
  'E4 7EN',
  51.631635,
  0.002215,
  'baby stay and play',
  '09:30',
  '10:30',
  'https://www.google.com/maps/search/?api=1&query=Chingford%20Library%20Chingford%20London%20E4%207EN',
  'https://www.walthamforest.gov.uk/events/stay-and-play-chingford-library-thursday',
  null,
  null,
  0,
  'Early years',
  'Waltham Forest',
  array['Thursday'],
  'FREQ=WEEKLY;BYDAY=TH',
  'Best Start in Life session. Check source page for temporary cancellations.',
  'Library-based stay-and-play session with toys, child social time, and space for parents and carers to meet.',
  'Free',
  false,
  'London Borough of Waltham Forest events',
  'https://www.walthamforest.gov.uk/events/stay-and-play-chingford-library-thursday'
),
(
  'Grow Wild Explorer: First session',
  'The Lloyd Park Centre, Winns Avenue Entrance, London E17 5JW',
  'E17 5JW',
  51.593406,
  -0.022032,
  'outdoor play',
  '09:30',
  '10:30',
  'https://www.google.com/maps/search/?api=1&query=The%20Lloyd%20Park%20Centre%20Winns%20Avenue%20Entrance%20E17%205JW',
  'https://www.walthamforest.gov.uk/events/grow-wild-explorer-first-session',
  null,
  null,
  0,
  'Under 5s',
  'Waltham Forest',
  array['Thursday'],
  'FREQ=WEEKLY;BYDAY=TH',
  'Best Start in Life weekly outdoor play session, term time only.',
  'Outdoor play in the Grow Wild natural adventure playground with climbing, sliding, hopping, jumping, and exploring.',
  'Free',
  false,
  'London Borough of Waltham Forest events',
  'https://www.walthamforest.gov.uk/events/grow-wild-explorer-first-session'
),
(
  'Flourish post-natal support group at Best Start Family Hub: Chingford',
  'Chingford Family Hub, Wyemead Centre, 5 Oaks Grove, Chingford E4 6EY',
  'E4 6EY',
  51.625359,
  0.009538,
  'post-natal support',
  '10:00',
  '12:00',
  'https://www.google.com/maps/search/?api=1&query=Chingford%20Family%20Hub%20Wyemead%20Centre%205%20Oaks%20Grove%20E4%206EY',
  'https://www.walthamforest.gov.uk/events/flourish-post-natal-support-group-best-start-family-hub-chingford',
  null,
  null,
  0,
  'Mothers with babies',
  'Waltham Forest',
  array['Monday'],
  'FREQ=WEEKLY;BYDAY=MO',
  'Invite-only Best Start in Life weekly session, term time only.',
  'Support group for mothers navigating the transition into motherhood, including space to talk, share, and have fun with baby.',
  'Free',
  true,
  'London Borough of Waltham Forest events',
  'https://www.walthamforest.gov.uk/events/flourish-post-natal-support-group-best-start-family-hub-chingford'
),
(
  'Sensory Play and Learn at Best Start Family Hub: Leytonstone',
  'Leytonstone Family Hub, The Junction, 2-8 Cathall Road, London E11 4LF',
  'E11 4LF',
  51.558130,
  0.006474,
  'sensory play',
  '10:00',
  '11:30',
  'https://www.google.com/maps/search/?api=1&query=Leytonstone%20Family%20Hub%20The%20Junction%202-8%20Cathall%20Road%20E11%204LF',
  'https://www.walthamforest.gov.uk/events/sensory-play-and-learn-best-start-family-hub-leytonstone',
  null,
  null,
  0,
  'Under 5s, including children with SEND or developmental delay',
  'Waltham Forest',
  array['Monday'],
  'FREQ=WEEKLY;BYDAY=MO',
  'Best Start in Life weekly session, term time only. Drop-in; booking not necessary according to the source page.',
  'Inclusive sensory play session for under-fives, including children with SEND or developmental delay.',
  'Free',
  false,
  'London Borough of Waltham Forest events',
  'https://www.walthamforest.gov.uk/events/sensory-play-and-learn-best-start-family-hub-leytonstone'
),
(
  'Stay and play at Lea Bridge Library: Monday',
  'Lea Bridge Library, Lea Bridge Road, London E10 7HU',
  'E10 7HU',
  51.570502,
  -0.024151,
  'baby stay and play',
  '11:00',
  '12:00',
  'https://www.google.com/maps/search/?api=1&query=Lea%20Bridge%20Library%20Lea%20Bridge%20Road%20London%20E10%207HU',
  'https://www.walthamforest.gov.uk/events/stay-and-play-lea-bridge-library-monday',
  null,
  null,
  0,
  'Babies and children',
  'Waltham Forest',
  array['Monday'],
  'FREQ=WEEKLY;BYDAY=MO',
  'Ongoing Best Start in Life weekly session. No booking required according to the source page.',
  'Library stay-and-play session with toys, parent/carer social time, and child social play.',
  'Free',
  false,
  'London Borough of Waltham Forest events',
  'https://www.walthamforest.gov.uk/events/stay-and-play-lea-bridge-library-monday'
),
(
  'HENRY infant feeding group drop-in at Walthamstow Library',
  'Walthamstow Library, High Street, London E17 7JN',
  'E17 7JN',
  51.584478,
  -0.021034,
  'infant feeding support',
  '11:00',
  '12:30',
  'https://www.google.com/maps/search/?api=1&query=Walthamstow%20Library%20High%20Street%20London%20E17%207JN',
  'https://www.walthamforest.gov.uk/events/henry-infant-feeding-group-drop-walthamstow-library',
  null,
  null,
  0,
  'Parents feeding babies',
  'Waltham Forest',
  array['Wednesday'],
  'FREQ=WEEKLY;BYDAY=WE',
  'Best Start in Life session provided by HENRY. Check source page for exact upcoming dates.',
  'Infant feeding support group for breast, bottle, and mixed feeding with trained practitioners.',
  'Free',
  false,
  'London Borough of Waltham Forest events',
  'https://www.walthamforest.gov.uk/events/henry-infant-feeding-group-drop-walthamstow-library'
),
(
  'Stay and Play at Walthamstow Library: Afternoon session',
  'Walthamstow Library, High Street, London E17 7JN',
  'E17 7JN',
  51.584478,
  -0.021034,
  'baby stay and play',
  '12:00',
  '13:00',
  'https://www.google.com/maps/search/?api=1&query=Walthamstow%20Library%20High%20Street%20London%20E17%207JN',
  'https://www.walthamforest.gov.uk/events/stay-and-play-walthamstow-library-afternoon-session',
  null,
  null,
  0,
  'Under 5s',
  'Waltham Forest',
  array['Wednesday', 'Friday'],
  'FREQ=WEEKLY;BYDAY=WE,FR',
  'Best Start in Life weekly session. Source page says every Wednesday and Friday from 12 noon to 1pm.',
  'Afternoon library stay-and-play session in the children''s area for under-fives and parents/carers.',
  'Free',
  true,
  'London Borough of Waltham Forest events',
  'https://www.walthamforest.gov.uk/events/stay-and-play-walthamstow-library-afternoon-session'
),
(
  'Stay and Play at Walthamstow Library: Morning session',
  'Walthamstow Library, High Street, London E17 7JN',
  'E17 7JN',
  51.584478,
  -0.021034,
  'baby stay and play',
  '09:30',
  '10:30',
  'https://www.google.com/maps/search/?api=1&query=Walthamstow%20Library%20High%20Street%20London%20E17%207JN',
  'https://www.walthamforest.gov.uk/events/stay-and-play-walthamstow-library-morning-session',
  null,
  null,
  0,
  'Under 5s',
  'Waltham Forest',
  array['Wednesday'],
  'FREQ=WEEKLY;BYDAY=WE',
  'Best Start in Life weekly session. Source page says every Wednesday 9:30am to 10:30am, term time only.',
  'Morning library stay-and-play session in the children''s area for under-fives and parents/carers.',
  'Free',
  true,
  'London Borough of Waltham Forest events',
  'https://www.walthamforest.gov.uk/events/stay-and-play-walthamstow-library-morning-session'
),
(
  'Stay and play at Leytonstone Library: Wednesday',
  'Leytonstone Library Plus, 6 Church Lane, London E11 1HG',
  'E11 1HG',
  51.568230,
  0.008982,
  'baby stay and play',
  '09:30',
  '11:30',
  'https://www.google.com/maps/search/?api=1&query=Leytonstone%20Library%20Plus%206%20Church%20Lane%20London%20E11%201HG',
  'https://www.walthamforest.gov.uk/events/stay-and-play-leytonstone-library-wednesday',
  null,
  null,
  0,
  'Under 5s',
  'Waltham Forest',
  array['Wednesday'],
  'FREQ=WEEKLY;BYDAY=WE',
  'Best Start in Life weekly session. Source page links to Eventbrite booking.',
  'Free play stay-and-play session for under-fives at Leytonstone Library.',
  'Free',
  true,
  'London Borough of Waltham Forest events',
  'https://www.walthamforest.gov.uk/events/stay-and-play-leytonstone-library-wednesday'
),
(
  'Stay and play at Lea Bridge Library: Wednesday',
  'Lea Bridge Library, Lea Bridge Road, London E10 7HU',
  'E10 7HU',
  51.570502,
  -0.024151,
  'baby stay and play',
  '10:00',
  '12:00',
  'https://www.google.com/maps/search/?api=1&query=Lea%20Bridge%20Library%20Lea%20Bridge%20Road%20London%20E10%207HU',
  'https://www.walthamforest.gov.uk/events/stay-and-play-lea-bridge-library-wednesday',
  null,
  null,
  0,
  'All ages',
  'Waltham Forest',
  array['Wednesday'],
  'FREQ=WEEKLY;BYDAY=WE',
  'Best Start in Life weekly session. No booking required according to the source page.',
  'Stay-and-play coffee morning for babies, children, parents, and carers.',
  'Free',
  false,
  'London Borough of Waltham Forest events',
  'https://www.walthamforest.gov.uk/events/stay-and-play-lea-bridge-library-wednesday'
),
(
  'Stay and play at Wood Street Library',
  'Wood Street Library, 1 Troubridge Square, Walthamstow, London E17 3GN',
  'E17 3GN',
  51.587133,
  -0.004202,
  'baby stay and play',
  '11:00',
  '12:00',
  'https://www.google.com/maps/search/?api=1&query=Wood%20Street%20Library%201%20Troubridge%20Square%20Walthamstow%20E17%203GN',
  'https://www.walthamforest.gov.uk/events/stay-and-play-wood-street-library',
  null,
  null,
  0,
  '0 to 3 years',
  'Waltham Forest',
  array['Tuesday', 'Thursday'],
  'FREQ=WEEKLY;BYDAY=TU,TH',
  'Best Start in Life weekly session. Source page says every Tuesday and Thursday 11am to 12pm.',
  'Library stay-and-play session for babies and toddlers with toys and parent/carer social time.',
  'Free',
  true,
  'London Borough of Waltham Forest events',
  'https://www.walthamforest.gov.uk/events/stay-and-play-wood-street-library'
),
(
  'Stay and Play at Chingford Library, Tuesday',
  'Chingford Library, Chingford, London E4 7EN',
  'E4 7EN',
  51.631635,
  0.002215,
  'baby stay and play',
  '11:00',
  '12:00',
  'https://www.google.com/maps/search/?api=1&query=Chingford%20Library%20Chingford%20London%20E4%207EN',
  'https://www.walthamforest.gov.uk/events/stay-and-play-chingford-library-tuesday',
  null,
  null,
  0,
  'Early years',
  'Waltham Forest',
  array['Tuesday'],
  'FREQ=WEEKLY;BYDAY=TU',
  'Best Start in Life session delivered by Lloyd Park Children''s Charity.',
  'Library stay-and-play session with toys, child social time, and space for parents and carers to meet.',
  'Free',
  false,
  'London Borough of Waltham Forest events',
  'https://www.walthamforest.gov.uk/events/stay-and-play-chingford-library-tuesday'
)
on conflict (source_url) do update set
  activity_name = excluded.activity_name,
  address = excluded.address,
  postcode = excluded.postcode,
  lat = excluded.lat,
  long = excluded.long,
  category = excluded.category,
  start_time = excluded.start_time,
  end_time = excluded.end_time,
  google_link = excluded.google_link,
  website = excluded.website,
  child_friendly_score = excluded.child_friendly_score,
  app_rating = excluded.app_rating,
  number_of_reviews = excluded.number_of_reviews,
  age_suitability = excluded.age_suitability,
  borough = excluded.borough,
  days_of_week = excluded.days_of_week,
  recurrence_rule = excluded.recurrence_rule,
  schedule_notes = excluded.schedule_notes,
  description = excluded.description,
  cost = excluded.cost,
  booking_required = excluded.booking_required,
  source_name = excluded.source_name;
