-- Generated by scripts/enrich-activity-images.js

-- Generated at 2026-07-20T15:33:08.353Z

-- Organiser images are preferred; listing images are the fallback.

-- Cards without a usable website image render the in-app category illustration.

-- Always serve images securely in the HTTPS mobile app.
update public.activities
set
  image_url = regexp_replace(image_url, '^http://', 'https://', 'i'),
  updated_at = now()
where image_url ~* '^http://';

-- Remove interface assets, tracking pixels, and other non-activity images.
-- The client displays a category illustration whenever image_url is null.
update public.activities
set
  image_url = null,
  image_source_url = null,
  updated_at = now()
where coalesce(image_url, '') ~* '(favicon|icon|logo|wordmark|sprite|avatar|placeholder|apple-touch|/flags/|site-flag|country-selector|language-selector|facebook[.]com/tr|facebook[.]net/tr|doubleclick|google-analytics|tracking-pixel|/pixel[.]|pixel[.]gif|[.]svg(?:[?#]|$)|google-play|google_play|app-store|app_store|download-button|cookie|consent|newsletter|payment|checkout)';

-- Applies audited website images and clears legacy Google Places photo values.

with image_updates (
  activity_id,
  google_place_id,
  google_place_uri,
  google_photo_url,
  google_rating,
  google_user_rating_count,
  image_url,
  image_source_url
) as (
  values
    ('b5958592-e997-4ddf-a0da-97038056a82c'::uuid, 'ChIJ2zZUcFYbdkgRr792eVT2hUE'::text, 'https://maps.google.com/?cid=4721450627043344303&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA'::text, null::text, 5::numeric, 46::integer, 'https://www.missionbodyfit.com/quality_auto/904bc3_7b3f1a027f224e269e4201875204e9ad~mv2.jpg'::text, 'https://www.missionbodyfit.com/'::text)
)
update public.activities as activities
set
  google_place_id = coalesce(image_updates.google_place_id, activities.google_place_id),
  google_place_uri = coalesce(image_updates.google_place_uri, activities.google_place_uri),
  google_photo_url = null,
  google_rating = coalesce(image_updates.google_rating, activities.google_rating),
  google_user_rating_count = coalesce(image_updates.google_user_rating_count, activities.google_user_rating_count),
  image_url = image_updates.image_url,
  image_source_url = image_updates.image_source_url,
  updated_at = now()
from image_updates
where activities.activity_id = image_updates.activity_id;

