-- Generated by scripts/audit-cross-source-duplicates.js
-- Cross-source duplicate groups: 24; archived records: 25 of 2405 published activities.

begin;

with duplicate_groups (keeper_id, duplicate_ids) as (
  values
    ('03b0f706-010d-41ea-9dff-ff6dc1c50491'::uuid, array['446f3be0-6b5b-43c3-9e04-dd8678efa12b'::uuid]),
    ('1d8abd50-a5e8-49b7-9bf4-04d9753d12be'::uuid, array['030935f0-0244-4cb9-ac01-6fb8e0aec60b'::uuid]),
    ('240457a7-475e-44a3-b167-335b3d52e15b'::uuid, array['9fd5a606-8d99-45e4-a977-e273d690653d'::uuid]),
    ('4ef23c41-d476-41e1-a20b-e0fd46ae7dae'::uuid, array['969da575-2f14-4a38-affb-7a7bb3bfdfc5'::uuid]),
    ('6d87ab1d-34c4-434d-8369-c7f880c963b3'::uuid, array['7371ecb9-a82c-4f2a-9739-dd951740843d'::uuid]),
    ('c359c2f8-a5f6-46a7-bc75-398624de982b'::uuid, array['7fd6d9ad-5e25-44a5-aebc-79e14359ffb9'::uuid]),
    ('95f40a5b-1597-4286-a968-dac90bea4323'::uuid, array['bd00f7d9-bfe2-40e9-81bd-eda4669c10d1'::uuid]),
    ('2a6a3af2-0a50-4900-8200-d49935ec9d9e'::uuid, array['c5c8a009-5f7a-4bb0-bb72-fa6a0fdb0396'::uuid]),
    ('977e16bb-74f0-4243-a051-c2a0efad709f'::uuid, array['37ee601e-28f4-4107-8f45-002ee34843d9'::uuid]),
    ('13ca4da6-e4cc-48d6-a1e7-c7478e47656c'::uuid, array['daa8db89-c405-4371-82e8-e32e962dffc2'::uuid]),
    ('838de202-ccec-403e-8bab-d944bd05c186'::uuid, array['f5b594e3-d5f3-4e89-8841-d7c1cbf33320'::uuid]),
    ('677a4af1-dc76-47a1-8e91-02c01d30b2e1'::uuid, array['70985c69-f066-49a4-b329-7ea9a684bb96'::uuid, '9b9d9293-035e-467c-b484-e2fac41576e9'::uuid]),
    ('17ed83b1-13e8-442b-b365-942565fdbd06'::uuid, array['32365d59-ad06-4d4e-8eb4-e83f1abbfccb'::uuid]),
    ('3b7277cd-b9df-45d1-a9fc-99499cd16019'::uuid, array['f9b22eb5-1c66-47d2-b937-8d02eea4b99b'::uuid]),
    ('739e13b3-3474-40b3-be37-a649afb8faf3'::uuid, array['660ae615-49ca-4214-9d18-5b286b51fdb2'::uuid]),
    ('cd1cd65f-339c-4339-9bf4-1a8cdd1d5056'::uuid, array['a6b0f8bf-4017-4853-8c4e-5cd6ae137d97'::uuid]),
    ('4453bd23-fba1-4002-bf60-4281d73033d2'::uuid, array['83de4ee2-d049-40e0-91f2-22329bda9ed5'::uuid]),
    ('1490b536-4b8b-4066-8efd-d5c9b6eab710'::uuid, array['ce5fcb26-a7bd-4364-ad6c-dc196d2a7ca4'::uuid]),
    ('4a0f971e-7f45-4a79-93ad-a8ceddecd72b'::uuid, array['d24009b3-586f-41ce-87f0-d5a060b14675'::uuid]),
    ('33095799-f86f-4cf2-8d27-12315876b395'::uuid, array['73eb0336-f4b7-49ec-b3ed-3f99a1f1cb0f'::uuid]),
    ('83d3d223-c0b2-4e07-8df1-15396f71ea78'::uuid, array['bf4f3032-3791-41ce-92e1-16a75a166297'::uuid]),
    ('c6b0a6d8-7a34-43b1-af58-0bd11bf22b12'::uuid, array['b2d1da9f-81ba-4e79-928a-19d946fdd0c8'::uuid]),
    ('8c6702e6-f87f-4efb-a354-b4d6193784b5'::uuid, array['0ef842d5-12e9-4366-b014-9e491302b49e'::uuid]),
    ('67c4fe36-713f-453a-b315-66e78b70ba17'::uuid, array['4258c142-1c2f-4baa-95a2-79a257f552ce'::uuid])
), merged as (
  select
    groups.keeper_id,
    groups.duplicate_ids,
    min(activity.start_time) as start_time,
    max(activity.end_time) as end_time,
    min(activity.availability_start_date) as availability_start_date,
    max(activity.availability_end_date) as availability_end_date,
    coalesce((
      select array_agg(distinct date_value order by date_value)
      from public.activities source
      cross join lateral unnest(coalesce(source.available_dates, '{}'::date[])) as date_value
      where source.activity_id = any(array_append(groups.duplicate_ids, groups.keeper_id))
    ), '{}'::date[]) as available_dates
  from duplicate_groups groups
  join public.activities activity on activity.activity_id = any(array_append(groups.duplicate_ids, groups.keeper_id))
  group by groups.keeper_id, groups.duplicate_ids
)
update public.activities activity
set
  start_time = merged.start_time,
  end_time = merged.end_time,
  availability_start_date = merged.availability_start_date,
  availability_end_date = merged.availability_end_date,
  available_dates = merged.available_dates,
  schedule_notes = concat_ws(' ', activity.schedule_notes, 'Duplicate source listings consolidated.'),
  updated_at = now()
from merged
where activity.activity_id = merged.keeper_id;

with duplicate_groups (keeper_id, duplicate_ids) as (
  values
    ('03b0f706-010d-41ea-9dff-ff6dc1c50491'::uuid, array['446f3be0-6b5b-43c3-9e04-dd8678efa12b'::uuid]),
    ('1d8abd50-a5e8-49b7-9bf4-04d9753d12be'::uuid, array['030935f0-0244-4cb9-ac01-6fb8e0aec60b'::uuid]),
    ('240457a7-475e-44a3-b167-335b3d52e15b'::uuid, array['9fd5a606-8d99-45e4-a977-e273d690653d'::uuid]),
    ('4ef23c41-d476-41e1-a20b-e0fd46ae7dae'::uuid, array['969da575-2f14-4a38-affb-7a7bb3bfdfc5'::uuid]),
    ('6d87ab1d-34c4-434d-8369-c7f880c963b3'::uuid, array['7371ecb9-a82c-4f2a-9739-dd951740843d'::uuid]),
    ('c359c2f8-a5f6-46a7-bc75-398624de982b'::uuid, array['7fd6d9ad-5e25-44a5-aebc-79e14359ffb9'::uuid]),
    ('95f40a5b-1597-4286-a968-dac90bea4323'::uuid, array['bd00f7d9-bfe2-40e9-81bd-eda4669c10d1'::uuid]),
    ('2a6a3af2-0a50-4900-8200-d49935ec9d9e'::uuid, array['c5c8a009-5f7a-4bb0-bb72-fa6a0fdb0396'::uuid]),
    ('977e16bb-74f0-4243-a051-c2a0efad709f'::uuid, array['37ee601e-28f4-4107-8f45-002ee34843d9'::uuid]),
    ('13ca4da6-e4cc-48d6-a1e7-c7478e47656c'::uuid, array['daa8db89-c405-4371-82e8-e32e962dffc2'::uuid]),
    ('838de202-ccec-403e-8bab-d944bd05c186'::uuid, array['f5b594e3-d5f3-4e89-8841-d7c1cbf33320'::uuid]),
    ('677a4af1-dc76-47a1-8e91-02c01d30b2e1'::uuid, array['70985c69-f066-49a4-b329-7ea9a684bb96'::uuid, '9b9d9293-035e-467c-b484-e2fac41576e9'::uuid]),
    ('17ed83b1-13e8-442b-b365-942565fdbd06'::uuid, array['32365d59-ad06-4d4e-8eb4-e83f1abbfccb'::uuid]),
    ('3b7277cd-b9df-45d1-a9fc-99499cd16019'::uuid, array['f9b22eb5-1c66-47d2-b937-8d02eea4b99b'::uuid]),
    ('739e13b3-3474-40b3-be37-a649afb8faf3'::uuid, array['660ae615-49ca-4214-9d18-5b286b51fdb2'::uuid]),
    ('cd1cd65f-339c-4339-9bf4-1a8cdd1d5056'::uuid, array['a6b0f8bf-4017-4853-8c4e-5cd6ae137d97'::uuid]),
    ('4453bd23-fba1-4002-bf60-4281d73033d2'::uuid, array['83de4ee2-d049-40e0-91f2-22329bda9ed5'::uuid]),
    ('1490b536-4b8b-4066-8efd-d5c9b6eab710'::uuid, array['ce5fcb26-a7bd-4364-ad6c-dc196d2a7ca4'::uuid]),
    ('4a0f971e-7f45-4a79-93ad-a8ceddecd72b'::uuid, array['d24009b3-586f-41ce-87f0-d5a060b14675'::uuid]),
    ('33095799-f86f-4cf2-8d27-12315876b395'::uuid, array['73eb0336-f4b7-49ec-b3ed-3f99a1f1cb0f'::uuid]),
    ('83d3d223-c0b2-4e07-8df1-15396f71ea78'::uuid, array['bf4f3032-3791-41ce-92e1-16a75a166297'::uuid]),
    ('c6b0a6d8-7a34-43b1-af58-0bd11bf22b12'::uuid, array['b2d1da9f-81ba-4e79-928a-19d946fdd0c8'::uuid]),
    ('8c6702e6-f87f-4efb-a354-b4d6193784b5'::uuid, array['0ef842d5-12e9-4366-b014-9e491302b49e'::uuid]),
    ('67c4fe36-713f-453a-b315-66e78b70ba17'::uuid, array['4258c142-1c2f-4baa-95a2-79a257f552ce'::uuid])
)
update public.activities activity
set public_listing_status = 'archived', updated_at = now()
from duplicate_groups groups
where activity.activity_id = any(groups.duplicate_ids)
  and activity.public_listing_status = 'published';

commit;
