-- Generated by scripts/audit-activity-suitability.js
-- Archive only high-confidence unsuitable venues.
-- Other potentially relevant places remain available for editorial review.
with unsuitable_listings (activity_id, archive_reason) as (
  values
    ('e7ea00ab-939d-4655-95ab-0fe1b7a8c9a9'::uuid, 'Google Places listing is a restaurant or takeaway rather than a cafe'::text),
    ('582b5743-d94b-4d62-97ea-1c72a5a8d3c6'::uuid, 'Google Places listing is a restaurant or takeaway rather than a cafe'::text),
    ('e7366e4b-c93e-436a-8542-8919f21241b2'::uuid, 'Google Places listing is a restaurant or takeaway rather than a cafe'::text),
    ('bd6cc1de-d87e-4adb-816b-881ab66dd919'::uuid, 'Google Places listing is a restaurant or takeaway rather than a cafe'::text),
    ('11510707-05f4-431e-b74e-f44613a19c2b'::uuid, 'Google Places listing is a restaurant or takeaway rather than a cafe'::text),
    ('00bf1cae-a43e-4d02-92ec-2f1ba1c4a6ec'::uuid, 'Google Places listing is a restaurant or takeaway rather than a cafe'::text),
    ('70b0e65c-267a-438e-bd8a-7301a2c7892a'::uuid, 'Google Places listing is a restaurant or takeaway rather than a cafe'::text),
    ('c3c06b0e-8433-4ab7-a097-fd8ed966853a'::uuid, 'Google Places listing is a restaurant or takeaway rather than a cafe'::text),
    ('b3b7b96e-db88-47c9-9e20-49521eae1b93'::uuid, 'Google Places listing is a restaurant or takeaway rather than a cafe'::text),
    ('a513eeb6-0b34-4f62-af90-fa9c2cde0fe9'::uuid, 'Google Places listing is a restaurant or takeaway rather than a cafe'::text),
    ('f879b650-7c4e-4a46-9570-ac7b3a0c5093'::uuid, 'Google Places listing is a restaurant or takeaway rather than a cafe'::text),
    ('16e36b2f-9c2a-4e64-ae68-ebb857456389'::uuid, 'Google Places listing is a restaurant or takeaway rather than a cafe'::text),
    ('8cc78a9f-509a-468d-bff9-fefb9d686823'::uuid, 'Google Places listing is a restaurant or takeaway rather than a cafe'::text),
    ('b821f846-0c53-4184-beab-84c8c7eb2cf1'::uuid, 'Google Places listing is a restaurant or takeaway rather than a cafe'::text),
    ('7762bc00-6f91-43fb-8557-2a22f0adb518'::uuid, 'Google Places listing is a restaurant or takeaway rather than a cafe'::text),
    ('1f1b9f92-989d-4b1c-a02c-ff90c0601d79'::uuid, 'Google Places listing is a restaurant or takeaway rather than a cafe'::text),
    ('7793fdbd-be7b-4db8-a5c7-edc10087ebf7'::uuid, 'Google Places listing is a restaurant or takeaway rather than a cafe'::text),
    ('c546b225-f480-4ffe-b480-c6d241fb9de2'::uuid, 'Google Places listing is a restaurant or takeaway rather than a cafe'::text),
    ('7156687c-f779-4038-a772-5b6ae934dff2'::uuid, 'Google Places listing is a restaurant or takeaway rather than a cafe'::text),
    ('efa3c964-88fb-44c7-8d93-7def537176d7'::uuid, 'Google Places listing is a restaurant or takeaway rather than a cafe'::text),
    ('c95a027c-d9c7-4ae0-8580-95f4fd1e84ca'::uuid, 'Google Places listing is a restaurant or takeaway rather than a cafe'::text),
    ('9a7b72fa-84a2-439c-abab-e1e64f3e1208'::uuid, 'Google Places listing is a restaurant or takeaway rather than a cafe'::text),
    ('17411ef4-f56b-4284-969c-7031bac07475'::uuid, 'Google Places listing is a restaurant or takeaway rather than a cafe'::text),
    ('7922c34a-95a6-4ebc-8d23-a1d307b2490c'::uuid, 'Google Places listing is a restaurant or takeaway rather than a cafe'::text)
)
update public.activities as activity
set archive = true,
    public_listing_status = 'archived',
    archive_reason = unsuitable_listings.archive_reason,
    archived_at = coalesce(activity.archived_at, now()),
    updated_at = now()
from unsuitable_listings
where activity.activity_id = unsuitable_listings.activity_id
  and coalesce(activity.archive, false) = false
  and activity.public_listing_status = 'published';
