-- Generated by scripts/enrich-activity-images.js

-- Generated at 2026-07-09T21:47:34.013Z

-- Applies Google Places image metadata first, with website image fallbacks.

with image_updates (
  activity_id,
  google_place_id,
  google_place_uri,
  google_photo_url,
  google_rating,
  google_user_rating_count,
  image_url,
  image_source_url
) as (
  values
    ('52d65a4f-d98a-4584-b750-eee6cc095735'::uuid, null::text, null::text, null::text, null::numeric, null::integer, 'https://cdn.prgloo.com/media/e51e66edc09c42cc8ba1a026bee7a07c.jpg?width=968&height=1452'::text, 'https://news.hackney.gov.uk/news/clissold-park-splash-pad-returns-this-month'::text),
    ('6961f9be-69f4-4e0a-ab93-d942ed653d17'::uuid, null::text, null::text, null::text, null::numeric, null::integer, 'https://discover.org.uk/wp-content/uploads/2019/08/sm_StoryWorld_please_credit_Sorcha_Bridge-1.jpg'::text, 'https://discover.org.uk/'::text),
    ('3d9f305b-0274-49f6-9645-5b55bf6123b2'::uuid, null::text, null::text, null::text, null::numeric, null::integer, 'https://discover.org.uk/wp-content/uploads/2019/08/sm_StoryWorld_please_credit_Sorcha_Bridge-1.jpg'::text, 'https://discover.org.uk/'::text),
    ('c5c0a0c2-8a2c-4cb7-955e-2da3bf6f8952'::uuid, null::text, null::text, null::text, null::numeric, null::integer, 'https://discover.org.uk/wp-content/uploads/2026/06/Children-Story-by-Marc-Sethi_DSCF4374.jpg'::text, 'https://discover.org.uk/your-visit/'::text),
    ('ce3ed9bd-b6d6-4285-9ea0-7ab6bc9e153c'::uuid, null::text, null::text, null::text, null::numeric, null::integer, 'https://www.dreami.uk/images/hp-roller.jpg'::text, 'https://www.dreami.uk/'::text),
    ('f72d5548-fbb8-4d3c-b39b-77ba984ab26e'::uuid, null::text, null::text, null::text, null::numeric, null::integer, 'https://www.walthamforest.gov.uk/sites/default/files/styles/x_small_3_2_546_x_364_/public/2023-09/Flourish%2C%20post-natal%20%28Bilkis%29.png.webp?itok=pjVZ4wGX'::text, 'https://www.walthamforest.gov.uk/events/flourish-post-natal-support-group-best-start-family-hub-chingford'::text),
    ('046c4067-e310-4c7d-8347-986175d62d63'::uuid, null::text, null::text, null::text, null::numeric, null::integer, 'https://hackneycityfarm.co.uk/wp-content/uploads/2021/07/visit-hackney-city-farm-courtyard-hero.jpg'::text, 'https://hackneycityfarm.co.uk/visit/'::text),
    ('96576472-6aea-4b60-8f3b-369c8d1216d2'::uuid, null::text, null::text, null::text, null::numeric, null::integer, 'https://www.walthamforest.gov.uk/sites/default/files/styles/x_small_3_2_546_x_364_/public/2023-09/Spare%20outdoor%20play%20%28Carina%29.png.webp?itok=848vgjmL'::text, 'https://www.walthamforest.gov.uk/events/grow-wild-explorer-first-session'::text),
    ('357ef0a1-f89c-4ab1-9e2a-411de3257242'::uuid, null::text, null::text, null::text, null::numeric, null::integer, 'https://hackneycityfarm.co.uk/wp-content/uploads/2021/07/visit-hackney-city-farm-courtyard-hero.jpg'::text, 'https://hackneycityfarm.co.uk/visit/'::text),
    ('452f7175-6c22-4cbd-9565-e6616c886cb3'::uuid, null::text, null::text, null::text, null::numeric, null::integer, 'https://www.walthamforest.gov.uk/sites/default/files/styles/x_small_3_2_546_x_364_/public/2023-10/HENRY%20baby%20pic.jpg.png.webp?itok=foLe-Qg8'::text, 'https://www.walthamforest.gov.uk/events/henry-infant-feeding-group-drop-walthamstow-library'::text),
    ('850dd0bd-16ac-4950-aafd-f307a5e68e34'::uuid, null::text, null::text, null::text, null::numeric, null::integer, 'http://static1.squarespace.com/static/66755fb23394722bc30dd748/t/67c7707b70ef325eeb4736c4/1741123712340/IMG_7869.jpeg?format=1500w'::text, 'https://www.ittakesavillageplaycafe.com/'::text),
    ('4b24e03e-f482-4239-94d3-456a1130712a'::uuid, null::text, null::text, null::text, null::numeric, null::integer, 'https://static.wixstatic.com/media/29804b_a81d8a0c7ab0462c87dadd52a21479c8.png/v1/fit/w_2500,h_1330,al_c/29804b_a81d8a0c7ab0462c87dadd52a21479c8.png'::text, 'https://www.ledelicee17.co.uk/about-us'::text),
    ('bc52512f-3a6a-45fe-81ae-0f5134a230a5'::uuid, null::text, null::text, null::text, null::numeric, null::integer, 'https://www.walthamforest.gov.uk/sites/default/files/styles/large_3_2_2x/public/2023-04/Green%20Gym%20Image%201MB.png.webp?itok=KWSNcm4M'::text, 'https://www.walthamforest.gov.uk/libraries-arts-parks-and-leisure/parks-and-open-spaces/lloyd-park'::text),
    ('4cb4fc09-f53c-41dd-b5fb-7c51d399b17f'::uuid, null::text, null::text, null::text, null::numeric, null::integer, 'https://museumofthehome.org.uk/wp-content/uploads/2025/04/WrightWright_Museum-of-the-Home_Hoxton_Visit-2_%E2%95%95HuftonCrow_011-scaled.jpg'::text, 'https://museumofthehome.org.uk/plan-your-visit/'::text),
    ('07475041-5233-4491-8b78-afbef983a73e'::uuid, null::text, null::text, null::text, null::numeric, null::integer, 'https://www.walthamforest.gov.uk/sites/default/files/styles/x_small_3_2_546_x_364_/public/2023-09/Somewhere%20to%20Belong%20%28Hakim%29.png.webp?itok=gwgXYdc0'::text, 'https://www.walthamforest.gov.uk/events/play-and-learn-under-2s-best-start-family-hub-walthamstow'::text),
    ('8d930b6f-5469-477b-b5de-af6c3fe6730d'::uuid, null::text, null::text, null::text, null::numeric, null::integer, 'https://www.queenelizabetholympicpark.co.uk/sites/default/files/styles/meta_facebook/public/banner-slide-image/Queen%20Elizabeth%20Olympic%20Park%20%2814%29%20HEADER.jpg?itok=ZoOGOmdC'::text, 'https://www.queenelizabetholympicpark.co.uk/explore-park/parklands-and-playgrounds/playgrounds'::text),
    ('d42e4c12-3a63-4c57-a190-e99a5d9dde98'::uuid, null::text, null::text, null::text, null::numeric, null::integer, 'https://www.royaldocks.london/media/events/_landscapeX4/DeckChairs1200.jpg'::text, 'https://www.royaldocks.london/whats-on/summer-family-fun-at-kids-summer-splash'::text),
    ('9d33f7e3-b51f-442d-8e12-bbb6b8d4946e'::uuid, null::text, null::text, null::text, null::numeric, null::integer, 'https://www.walthamforest.gov.uk/sites/default/files/styles/x_small_3_2_546_x_364_/public/2023-09/Somewhere%20to%20Belong%20%28Hakim%29.png.webp?itok=gwgXYdc0'::text, 'https://www.walthamforest.gov.uk/events/sensory-play-and-learn-best-start-family-hub-leytonstone'::text),
    ('d8390919-93bc-49c3-b398-60b814bf0329'::uuid, null::text, null::text, null::text, null::numeric, null::integer, 'https://www.walthamforest.gov.uk/sites/default/files/styles/x_small_3_2_546_x_364_/public/2024-04/Music%20and%20Rhymes%20%28Carina%29.png.webp?itok=utgvVydq'::text, 'https://www.walthamforest.gov.uk/events/stay-and-play-barclay-primary-school-leyton'::text),
    ('7b404648-4cb8-4c09-af02-b57810d267d9'::uuid, null::text, null::text, null::text, null::numeric, null::integer, 'https://www.walthamforest.gov.uk/sites/default/files/styles/x_small_3_2_546_x_364_/public/2023-09/Spare%20-%20baby%20play%20%28Carina%29.png.webp?itok=18rYIs5X'::text, 'https://www.walthamforest.gov.uk/events/stay-and-play-chingford-library-thursday'::text),
    ('66a17506-dc67-439b-9b52-1c8a9d191c44'::uuid, null::text, null::text, null::text, null::numeric, null::integer, 'https://www.walthamforest.gov.uk/sites/default/files/styles/x_small_3_2_546_x_364_/public/2023-09/Spare%20-%20baby%20play%20%28Carina%29.png.webp?itok=18rYIs5X'::text, 'https://www.walthamforest.gov.uk/events/stay-and-play-chingford-library-tuesday'::text),
    ('e3a9f56c-b0a3-4d1f-91c3-204e0a61fc8e'::uuid, null::text, null::text, null::text, null::numeric, null::integer, 'https://www.walthamforest.gov.uk/sites/default/files/styles/x_small_3_2_546_x_364_/public/2024-04/Music%20and%20Rhymes%20%28Carina%29.png.webp?itok=utgvVydq'::text, 'https://www.walthamforest.gov.uk/events/stay-and-play-lea-bridge-library-monday'::text),
    ('b1667cf4-c749-49a2-b114-efd45cbee448'::uuid, null::text, null::text, null::text, null::numeric, null::integer, 'https://www.walthamforest.gov.uk/sites/default/files/styles/x_small_3_2_546_x_364_/public/2023-09/Spare%20-%20baby%20play%20%28Carina%29.png.webp?itok=18rYIs5X'::text, 'https://www.walthamforest.gov.uk/events/stay-and-play-lea-bridge-library-wednesday'::text),
    ('ea000dd1-210c-4fed-8d0c-c46f4ee268b8'::uuid, null::text, null::text, null::text, null::numeric, null::integer, 'https://www.walthamforest.gov.uk/sites/default/files/styles/x_small_3_2_546_x_364_/public/2023-09/Baby%20bank%20play%20sessions%20%28Carina%29.png.webp?itok=S-aPYjR5'::text, 'https://www.walthamforest.gov.uk/events/stay-and-play-leytonstone-library-wednesday'::text),
    ('e6b85611-303e-4ac0-b0b9-dff289c65c66'::uuid, null::text, null::text, null::text, null::numeric, null::integer, 'https://www.walthamforest.gov.uk/sites/default/files/styles/x_small_3_2_546_x_364_/public/2023-09/Spares%20%28Carina%29%20toddlers%20playing.png.webp?itok=563lbQAw'::text, 'https://www.walthamforest.gov.uk/events/stay-and-play-walthamstow-library-afternoon-session'::text),
    ('76308234-3d25-4215-895a-f4837a883e39'::uuid, null::text, null::text, null::text, null::numeric, null::integer, 'https://www.walthamforest.gov.uk/sites/default/files/styles/x_small_3_2_546_x_364_/public/2023-09/Spares%20%28Carina%29%20toddlers%20playing.png.webp?itok=563lbQAw'::text, 'https://www.walthamforest.gov.uk/events/stay-and-play-walthamstow-library-morning-session'::text),
    ('d90e11c4-1026-4345-acb9-d91a5fb4d7ab'::uuid, null::text, null::text, null::text, null::numeric, null::integer, 'https://www.walthamforest.gov.uk/sites/default/files/styles/x_small_3_2_546_x_364_/public/2023-09/Under%202s%20play%20session%20%28Carina%29.png.webp?itok=VM4t8jTQ'::text, 'https://www.walthamforest.gov.uk/events/stay-and-play-wood-street-library'::text),
    ('015ce13d-2869-470f-bbb6-2284e6450309'::uuid, null::text, null::text, null::text, null::numeric, null::integer, 'https://highamspark.london/wp-content/uploads/2019/06/maxresdefault.jpg'::text, 'https://highamspark.london/highams-park/the-highams-park/'::text),
    ('623611c4-da1e-4992-8df5-76521594a237'::uuid, null::text, null::text, null::text, null::numeric, null::integer, 'https://www.queenelizabetholympicpark.co.uk/sites/default/files/styles/meta_facebook/public/banner-slide-image/timber-lodge_spring2024_terrace%20%281%29_0.jpg?itok=4GgQ0caA'::text, 'https://www.queenelizabetholympicpark.co.uk/eat-drink/timber-lodge-cafe-your-parkside-dining-destination'::text),
    ('350a59ef-f5c7-4123-ad8e-859e3464193d'::uuid, null::text, null::text, null::text, null::numeric, null::integer, 'https://www.queenelizabetholympicpark.co.uk/sites/default/files/styles/meta_facebook/public/banner-slide-image/_CSP4480%20v3%201220x498.jpg?itok=eyVX5N9r'::text, 'https://www.queenelizabetholympicpark.co.uk/explore-park/parklands-and-playgrounds/tumbling-bay-playground'::text),
    ('fb02fa67-daa7-4ebe-b4dd-11a62e93a1bd'::uuid, null::text, null::text, null::text, null::numeric, null::integer, 'https://www.wildlondon.org.uk/sites/default/files/styles/large/public/2024-07/RS5999_CHURCH_ELEANOR-4690_lpr.jpg?itok=gMTWuakq'::text, 'https://www.wildlondon.org.uk/nature-reserves/walthamstow-wetlands'::text),
    ('a23a8ef5-2f30-4ed7-9703-6bf1f861b158'::uuid, null::text, null::text, null::text, null::numeric, null::integer, 'https://www.cityoflondon.gov.uk/things-to-do/green-spaces/west-ham-park/www.cityoflondon.gov.uk/image-library/Images/Green-Spaces/ornamental-gardens.x0b7e2ba6.jpg?w=1200&q=70'::text, 'https://www.cityoflondon.gov.uk/things-to-do/green-spaces/west-ham-park/visit-west-ham-park'::text),
    ('1bcc8da5-62ac-43d8-81fb-9f47e285cfe8'::uuid, null::text, null::text, null::text, null::numeric, null::integer, 'https://www.walthamforest.gov.uk/sites/default/files/styles/x_small_3_2_546_x_364_/public/2026-06/IMG_4880.JPG.webp?itok=QSYZb1Fl'::text, 'https://www.walthamforest.gov.uk/events/william-morris-gallery-family-day-park-morriss-magical-menagerie'::text),
    ('ce5fcb26-a7bd-4364-ad6c-dc196d2a7ca4'::uuid, null::text, null::text, null::text, null::numeric, null::integer, 'https://www.wmgallery.org.uk/wp-content/themes/WMGgit/assets/william-morris-gallery_OG-image.jpg'::text, 'https://www.wmgallery.org.uk/learn/families/'::text),
    ('d4a5041c-15b6-4c26-889d-5b0a4ed6ffff'::uuid, null::text, null::text, null::text, null::numeric, null::integer, 'https://eschoolscms.blob.core.windows.net/production/images/hNoUNmvYBdet6EBSyoWjRr2repuTCxusz15LMhVB.jpg'::text, 'https://www.woodberrydowncfhub.hackney.gov.uk/'::text)
)
update public.activities as activities
set
  google_place_id = coalesce(image_updates.google_place_id, activities.google_place_id),
  google_place_uri = coalesce(image_updates.google_place_uri, activities.google_place_uri),
  google_photo_url = coalesce(image_updates.google_photo_url, activities.google_photo_url),
  google_rating = coalesce(image_updates.google_rating, activities.google_rating),
  google_user_rating_count = coalesce(image_updates.google_user_rating_count, activities.google_user_rating_count),
  image_url = coalesce(image_updates.image_url, activities.image_url),
  image_source_url = coalesce(image_updates.image_source_url, activities.image_source_url),
  updated_at = now()
from image_updates
where activities.activity_id = image_updates.activity_id;

