-- Generated by scripts/audit-cross-source-duplicates.js
-- 3331 active records audited; 13 exact duplicate groups; 13 proposed archives.
-- Existing reviews and plans remain attached to archived records. No dates or times are merged.
begin;
update public.activities activity
set archive = true,
    public_listing_status = 'archived',
    archive_reason = 'Duplicate of 0ee8b728-c788-4fca-a0ab-333d849b86f6: same activity, venue and session',
    archived_at = coalesce(archived_at, now()),
    updated_at = now()
where activity.activity_id = '684ff48b-09db-470f-af80-2ca967ca1962'::uuid
  and activity.updated_at = '2026-09-13 11:52:03.781599+00'::timestamptz
  and activity.archive = false
  and activity.public_listing_status in ('draft', 'published')
  and activity.admin_cover_image_url is null
  and activity.reviewed_image_url is null
  and activity.reviewed_image_selected_at is null
  and activity.user_image_url is null
  and activity.use_category_image is not true
  and activity.image_review_approved_at is null
  and not exists (select 1 from public.activity_reviews history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.comments_table history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.activity_photos history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.activity_swipes history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.activity_shortlist history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.activity_user_statuses history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.calendar_events history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.activity_image_manual_reviews history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.activity_curation_feedback history where history.activity_id = activity.activity_id)
  and exists (
    select 1 from public.activities keeper
    where keeper.activity_id = '0ee8b728-c788-4fca-a0ab-333d849b86f6'::uuid
      and keeper.archive = false
      and keeper.public_listing_status in ('draft', 'published')
      and keeper.updated_at = '2026-09-16 10:05:52.906151+00'::timestamptz
  );

update public.activities activity
set archive = true,
    public_listing_status = 'archived',
    archive_reason = 'Duplicate of 28e64fe9-8d1d-420e-9097-d8528b4a5cc9: same activity, venue and session',
    archived_at = coalesce(archived_at, now()),
    updated_at = now()
where activity.activity_id = '305fa7dc-47cd-40b8-a193-55fe8edb3f5b'::uuid
  and activity.updated_at = '2026-09-13 11:52:03.781599+00'::timestamptz
  and activity.archive = false
  and activity.public_listing_status in ('draft', 'published')
  and activity.admin_cover_image_url is null
  and activity.reviewed_image_url is null
  and activity.reviewed_image_selected_at is null
  and activity.user_image_url is null
  and activity.use_category_image is not true
  and activity.image_review_approved_at is null
  and not exists (select 1 from public.activity_reviews history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.comments_table history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.activity_photos history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.activity_swipes history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.activity_shortlist history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.activity_user_statuses history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.calendar_events history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.activity_image_manual_reviews history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.activity_curation_feedback history where history.activity_id = activity.activity_id)
  and exists (
    select 1 from public.activities keeper
    where keeper.activity_id = '28e64fe9-8d1d-420e-9097-d8528b4a5cc9'::uuid
      and keeper.archive = false
      and keeper.public_listing_status in ('draft', 'published')
      and keeper.updated_at = '2026-09-13 11:52:03.781599+00'::timestamptz
  );

update public.activities activity
set archive = true,
    public_listing_status = 'archived',
    archive_reason = 'Duplicate of 32fbc3d0-59ed-4860-baec-bd8a4c4f3289: same activity, venue and session',
    archived_at = coalesce(archived_at, now()),
    updated_at = now()
where activity.activity_id = '8c8ad1a1-587b-497f-b633-49898b90df67'::uuid
  and activity.updated_at = '2026-09-13 11:52:03.781599+00'::timestamptz
  and activity.archive = false
  and activity.public_listing_status in ('draft', 'published')
  and activity.admin_cover_image_url is null
  and activity.reviewed_image_url is null
  and activity.reviewed_image_selected_at is null
  and activity.user_image_url is null
  and activity.use_category_image is not true
  and activity.image_review_approved_at is null
  and not exists (select 1 from public.activity_reviews history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.comments_table history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.activity_photos history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.activity_swipes history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.activity_shortlist history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.activity_user_statuses history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.calendar_events history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.activity_image_manual_reviews history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.activity_curation_feedback history where history.activity_id = activity.activity_id)
  and exists (
    select 1 from public.activities keeper
    where keeper.activity_id = '32fbc3d0-59ed-4860-baec-bd8a4c4f3289'::uuid
      and keeper.archive = false
      and keeper.public_listing_status in ('draft', 'published')
      and keeper.updated_at = '2026-09-13 11:52:03.781599+00'::timestamptz
  );

update public.activities activity
set archive = true,
    public_listing_status = 'archived',
    archive_reason = 'Duplicate of 865afb81-d1fb-45c7-bca5-de97921a930f: same activity, venue and session',
    archived_at = coalesce(archived_at, now()),
    updated_at = now()
where activity.activity_id = '3881a2d3-5ff2-4985-8bd3-8f595a6d62cb'::uuid
  and activity.updated_at = '2026-09-13 11:52:03.781599+00'::timestamptz
  and activity.archive = false
  and activity.public_listing_status in ('draft', 'published')
  and activity.admin_cover_image_url is null
  and activity.reviewed_image_url is null
  and activity.reviewed_image_selected_at is null
  and activity.user_image_url is null
  and activity.use_category_image is not true
  and activity.image_review_approved_at is null
  and not exists (select 1 from public.activity_reviews history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.comments_table history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.activity_photos history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.activity_swipes history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.activity_shortlist history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.activity_user_statuses history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.calendar_events history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.activity_image_manual_reviews history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.activity_curation_feedback history where history.activity_id = activity.activity_id)
  and exists (
    select 1 from public.activities keeper
    where keeper.activity_id = '865afb81-d1fb-45c7-bca5-de97921a930f'::uuid
      and keeper.archive = false
      and keeper.public_listing_status in ('draft', 'published')
      and keeper.updated_at = '2026-09-13 11:52:03.781599+00'::timestamptz
  );

update public.activities activity
set archive = true,
    public_listing_status = 'archived',
    archive_reason = 'Duplicate of 3df3226a-dbc0-4aba-868d-3fcb4ed80e27: same activity, venue and session',
    archived_at = coalesce(archived_at, now()),
    updated_at = now()
where activity.activity_id = 'f9d44f5a-a2ea-43a4-b28b-b6f9cef4c685'::uuid
  and activity.updated_at = '2026-09-13 11:52:03.781599+00'::timestamptz
  and activity.archive = false
  and activity.public_listing_status in ('draft', 'published')
  and activity.admin_cover_image_url is null
  and activity.reviewed_image_url is null
  and activity.reviewed_image_selected_at is null
  and activity.user_image_url is null
  and activity.use_category_image is not true
  and activity.image_review_approved_at is null
  and not exists (select 1 from public.activity_reviews history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.comments_table history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.activity_photos history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.activity_swipes history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.activity_shortlist history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.activity_user_statuses history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.calendar_events history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.activity_image_manual_reviews history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.activity_curation_feedback history where history.activity_id = activity.activity_id)
  and exists (
    select 1 from public.activities keeper
    where keeper.activity_id = '3df3226a-dbc0-4aba-868d-3fcb4ed80e27'::uuid
      and keeper.archive = false
      and keeper.public_listing_status in ('draft', 'published')
      and keeper.updated_at = '2026-09-13 11:52:03.781599+00'::timestamptz
  );

update public.activities activity
set archive = true,
    public_listing_status = 'archived',
    archive_reason = 'Duplicate of 67e51f71-8e06-4bfb-a2aa-f7197f1f2749: same activity, venue and session',
    archived_at = coalesce(archived_at, now()),
    updated_at = now()
where activity.activity_id = '580ee1fb-b041-453a-8948-2b67bf8a755d'::uuid
  and activity.updated_at = '2026-09-13 12:20:56.574613+00'::timestamptz
  and activity.archive = false
  and activity.public_listing_status in ('draft', 'published')
  and activity.admin_cover_image_url is null
  and activity.reviewed_image_url is null
  and activity.reviewed_image_selected_at is null
  and activity.user_image_url is null
  and activity.use_category_image is not true
  and activity.image_review_approved_at is null
  and not exists (select 1 from public.activity_reviews history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.comments_table history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.activity_photos history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.activity_swipes history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.activity_shortlist history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.activity_user_statuses history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.calendar_events history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.activity_image_manual_reviews history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.activity_curation_feedback history where history.activity_id = activity.activity_id)
  and exists (
    select 1 from public.activities keeper
    where keeper.activity_id = '67e51f71-8e06-4bfb-a2aa-f7197f1f2749'::uuid
      and keeper.archive = false
      and keeper.public_listing_status in ('draft', 'published')
      and keeper.updated_at = '2026-09-13 11:52:03.781599+00'::timestamptz
  );

update public.activities activity
set archive = true,
    public_listing_status = 'archived',
    archive_reason = 'Duplicate of 90b6fb58-3457-4f5b-b74e-13317ed77762: same activity, venue and session',
    archived_at = coalesce(archived_at, now()),
    updated_at = now()
where activity.activity_id = '5a9dfc36-c860-4177-ac1f-4cea6dee7c31'::uuid
  and activity.updated_at = '2026-09-13 11:52:03.781599+00'::timestamptz
  and activity.archive = false
  and activity.public_listing_status in ('draft', 'published')
  and activity.admin_cover_image_url is null
  and activity.reviewed_image_url is null
  and activity.reviewed_image_selected_at is null
  and activity.user_image_url is null
  and activity.use_category_image is not true
  and activity.image_review_approved_at is null
  and not exists (select 1 from public.activity_reviews history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.comments_table history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.activity_photos history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.activity_swipes history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.activity_shortlist history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.activity_user_statuses history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.calendar_events history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.activity_image_manual_reviews history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.activity_curation_feedback history where history.activity_id = activity.activity_id)
  and exists (
    select 1 from public.activities keeper
    where keeper.activity_id = '90b6fb58-3457-4f5b-b74e-13317ed77762'::uuid
      and keeper.archive = false
      and keeper.public_listing_status in ('draft', 'published')
      and keeper.updated_at = '2026-09-13 12:20:56.574613+00'::timestamptz
  );

update public.activities activity
set archive = true,
    public_listing_status = 'archived',
    archive_reason = 'Duplicate of 66646f1f-cee5-4971-8d6d-1d76bc23c5da: same activity, venue and session',
    archived_at = coalesce(archived_at, now()),
    updated_at = now()
where activity.activity_id = 'a3866ece-91ea-497a-871c-d4f0f3f6dfb9'::uuid
  and activity.updated_at = '2026-09-13 11:52:03.781599+00'::timestamptz
  and activity.archive = false
  and activity.public_listing_status in ('draft', 'published')
  and activity.admin_cover_image_url is null
  and activity.reviewed_image_url is null
  and activity.reviewed_image_selected_at is null
  and activity.user_image_url is null
  and activity.use_category_image is not true
  and activity.image_review_approved_at is null
  and not exists (select 1 from public.activity_reviews history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.comments_table history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.activity_photos history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.activity_swipes history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.activity_shortlist history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.activity_user_statuses history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.calendar_events history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.activity_image_manual_reviews history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.activity_curation_feedback history where history.activity_id = activity.activity_id)
  and exists (
    select 1 from public.activities keeper
    where keeper.activity_id = '66646f1f-cee5-4971-8d6d-1d76bc23c5da'::uuid
      and keeper.archive = false
      and keeper.public_listing_status in ('draft', 'published')
      and keeper.updated_at = '2026-09-13 11:52:03.781599+00'::timestamptz
  );

update public.activities activity
set archive = true,
    public_listing_status = 'archived',
    archive_reason = 'Duplicate of ca790bfe-05f5-4491-9b89-0de28c7316a9: same activity, venue and session',
    archived_at = coalesce(archived_at, now()),
    updated_at = now()
where activity.activity_id = '68eb13eb-e428-4ce1-82eb-bb332dbb9fbf'::uuid
  and activity.updated_at = '2026-09-13 11:52:03.781599+00'::timestamptz
  and activity.archive = false
  and activity.public_listing_status in ('draft', 'published')
  and activity.admin_cover_image_url is null
  and activity.reviewed_image_url is null
  and activity.reviewed_image_selected_at is null
  and activity.user_image_url is null
  and activity.use_category_image is not true
  and activity.image_review_approved_at is null
  and not exists (select 1 from public.activity_reviews history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.comments_table history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.activity_photos history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.activity_swipes history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.activity_shortlist history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.activity_user_statuses history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.calendar_events history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.activity_image_manual_reviews history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.activity_curation_feedback history where history.activity_id = activity.activity_id)
  and exists (
    select 1 from public.activities keeper
    where keeper.activity_id = 'ca790bfe-05f5-4491-9b89-0de28c7316a9'::uuid
      and keeper.archive = false
      and keeper.public_listing_status in ('draft', 'published')
      and keeper.updated_at = '2026-09-13 11:52:03.781599+00'::timestamptz
  );

update public.activities activity
set archive = true,
    public_listing_status = 'archived',
    archive_reason = 'Duplicate of cc1cfc66-86cd-4066-9da0-ac1f602f5d4e: same activity, venue and session',
    archived_at = coalesce(archived_at, now()),
    updated_at = now()
where activity.activity_id = '7ee2072f-6f9b-49ad-92db-3f78843b7ece'::uuid
  and activity.updated_at = '2026-09-13 11:52:03.781599+00'::timestamptz
  and activity.archive = false
  and activity.public_listing_status in ('draft', 'published')
  and activity.admin_cover_image_url is null
  and activity.reviewed_image_url is null
  and activity.reviewed_image_selected_at is null
  and activity.user_image_url is null
  and activity.use_category_image is not true
  and activity.image_review_approved_at is null
  and not exists (select 1 from public.activity_reviews history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.comments_table history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.activity_photos history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.activity_swipes history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.activity_shortlist history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.activity_user_statuses history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.calendar_events history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.activity_image_manual_reviews history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.activity_curation_feedback history where history.activity_id = activity.activity_id)
  and exists (
    select 1 from public.activities keeper
    where keeper.activity_id = 'cc1cfc66-86cd-4066-9da0-ac1f602f5d4e'::uuid
      and keeper.archive = false
      and keeper.public_listing_status in ('draft', 'published')
      and keeper.updated_at = '2026-09-13 11:52:03.781599+00'::timestamptz
  );

update public.activities activity
set archive = true,
    public_listing_status = 'archived',
    archive_reason = 'Duplicate of 8748f27e-9ebe-4757-8643-169a0beb00c9: same activity, venue and session',
    archived_at = coalesce(archived_at, now()),
    updated_at = now()
where activity.activity_id = 'c27c9b2a-7940-4983-a59e-f10af63fb677'::uuid
  and activity.updated_at = '2026-09-13 16:12:32.327521+00'::timestamptz
  and activity.archive = false
  and activity.public_listing_status in ('draft', 'published')
  and activity.admin_cover_image_url is null
  and activity.reviewed_image_url is null
  and activity.reviewed_image_selected_at is null
  and activity.user_image_url is null
  and activity.use_category_image is not true
  and activity.image_review_approved_at is null
  and not exists (select 1 from public.activity_reviews history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.comments_table history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.activity_photos history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.activity_swipes history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.activity_shortlist history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.activity_user_statuses history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.calendar_events history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.activity_image_manual_reviews history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.activity_curation_feedback history where history.activity_id = activity.activity_id)
  and exists (
    select 1 from public.activities keeper
    where keeper.activity_id = '8748f27e-9ebe-4757-8643-169a0beb00c9'::uuid
      and keeper.archive = false
      and keeper.public_listing_status in ('draft', 'published')
      and keeper.updated_at = '2026-09-13 16:12:32.327521+00'::timestamptz
  );

update public.activities activity
set archive = true,
    public_listing_status = 'archived',
    archive_reason = 'Duplicate of 9bb2aba3-f43b-480d-8473-bf67d80d9662: same activity, venue and session',
    archived_at = coalesce(archived_at, now()),
    updated_at = now()
where activity.activity_id = 'caed0e86-0b86-4840-9011-653493290da6'::uuid
  and activity.updated_at = '2026-09-13 11:52:03.781599+00'::timestamptz
  and activity.archive = false
  and activity.public_listing_status in ('draft', 'published')
  and activity.admin_cover_image_url is null
  and activity.reviewed_image_url is null
  and activity.reviewed_image_selected_at is null
  and activity.user_image_url is null
  and activity.use_category_image is not true
  and activity.image_review_approved_at is null
  and not exists (select 1 from public.activity_reviews history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.comments_table history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.activity_photos history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.activity_swipes history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.activity_shortlist history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.activity_user_statuses history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.calendar_events history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.activity_image_manual_reviews history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.activity_curation_feedback history where history.activity_id = activity.activity_id)
  and exists (
    select 1 from public.activities keeper
    where keeper.activity_id = '9bb2aba3-f43b-480d-8473-bf67d80d9662'::uuid
      and keeper.archive = false
      and keeper.public_listing_status in ('draft', 'published')
      and keeper.updated_at = '2026-09-13 11:52:03.781599+00'::timestamptz
  );

update public.activities activity
set archive = true,
    public_listing_status = 'archived',
    archive_reason = 'Duplicate of f077a621-7fcc-41da-9190-2a7fd32dc4b8: same activity, venue and session',
    archived_at = coalesce(archived_at, now()),
    updated_at = now()
where activity.activity_id = 'e7da8492-6889-4031-803a-9be3b63163ce'::uuid
  and activity.updated_at = '2026-09-13 11:52:03.781599+00'::timestamptz
  and activity.archive = false
  and activity.public_listing_status in ('draft', 'published')
  and activity.admin_cover_image_url is null
  and activity.reviewed_image_url is null
  and activity.reviewed_image_selected_at is null
  and activity.user_image_url is null
  and activity.use_category_image is not true
  and activity.image_review_approved_at is null
  and not exists (select 1 from public.activity_reviews history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.comments_table history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.activity_photos history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.activity_swipes history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.activity_shortlist history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.activity_user_statuses history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.calendar_events history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.activity_image_manual_reviews history where history.activity_id = activity.activity_id)
  and not exists (select 1 from public.activity_curation_feedback history where history.activity_id = activity.activity_id)
  and exists (
    select 1 from public.activities keeper
    where keeper.activity_id = 'f077a621-7fcc-41da-9190-2a7fd32dc4b8'::uuid
      and keeper.archive = false
      and keeper.public_listing_status in ('draft', 'published')
      and keeper.updated_at = '2026-09-13 11:52:03.781599+00'::timestamptz
  );
commit;
