-- Generated by scripts/audit-cross-source-duplicates.js
-- Cross-source duplicate groups: 2; archived records: 4 of 3185 published activities.

begin;

with duplicate_groups (keeper_id, duplicate_ids) as (
  values
    ('31d09e5c-c485-4d41-9d5a-ce8740a53e70'::uuid, array['17b2076c-5f43-4f54-b195-2e457a18890f'::uuid]),
    ('5ff9af1e-b65a-4b49-bb47-9fd477366eb0'::uuid, array['985716f1-90d6-4687-84d5-9734840eaa46'::uuid, 'c089404c-ae62-47a0-943a-2bbebe2af6cc'::uuid, 'dc451af3-f4f0-47d6-b8d4-ce52d40f6fa9'::uuid])
), merged as (
  select
    groups.keeper_id,
    groups.duplicate_ids,
    min(activity.start_time) as start_time,
    max(activity.end_time) as end_time,
    min(activity.availability_start_date) as availability_start_date,
    max(activity.availability_end_date) as availability_end_date,
    coalesce((
      select array_agg(distinct date_value order by date_value)
      from public.activities source
      cross join lateral unnest(coalesce(source.available_dates, '{}'::date[])) as date_value
      where source.activity_id = any(array_append(groups.duplicate_ids, groups.keeper_id))
    ), '{}'::date[]) as available_dates
  from duplicate_groups groups
  join public.activities activity on activity.activity_id = any(array_append(groups.duplicate_ids, groups.keeper_id))
  group by groups.keeper_id, groups.duplicate_ids
)
update public.activities activity
set
  start_time = merged.start_time,
  end_time = merged.end_time,
  availability_start_date = merged.availability_start_date,
  availability_end_date = merged.availability_end_date,
  available_dates = merged.available_dates,
  schedule_notes = concat_ws(' ', activity.schedule_notes, 'Duplicate source listings consolidated.'),
  updated_at = now()
from merged
where activity.activity_id = merged.keeper_id;

with duplicate_groups (keeper_id, duplicate_ids) as (
  values
    ('31d09e5c-c485-4d41-9d5a-ce8740a53e70'::uuid, array['17b2076c-5f43-4f54-b195-2e457a18890f'::uuid]),
    ('5ff9af1e-b65a-4b49-bb47-9fd477366eb0'::uuid, array['985716f1-90d6-4687-84d5-9734840eaa46'::uuid, 'c089404c-ae62-47a0-943a-2bbebe2af6cc'::uuid, 'dc451af3-f4f0-47d6-b8d4-ce52d40f6fa9'::uuid])
)
update public.activities activity
set archive = true, public_listing_status = 'archived', updated_at = now()
from duplicate_groups groups
where activity.activity_id = any(groups.duplicate_ids)
  and activity.public_listing_status = 'published';

commit;
