-- Generated by scripts/enrich-wikimedia-from-osm.js
-- Exact OSM name-and-location matches: 11 of 2117 London activities searched.
with image_updates (activity_id, wikimedia_image_url) as (values
  ('c42df144-7c4c-47ba-be12-65838b8e4c10'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Here_lies_Joey........_-_geograph.org.uk_-_3278456.jpg/960px-Here_lies_Joey........_-_geograph.org.uk_-_3278456.jpg'::text),
  ('31bc3ee6-bb3f-4eef-8ecb-4b5e98698ecc'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/190_of_%27The_History_and_Antiquities_of_London%2C_Westminster%2C_Southwark%2C_and_parts_adjacent%2C_etc%27_%2811013597895%29.jpg/960px-190_of_%27The_History_and_Antiquities_of_London%2C_Westminster%2C_Southwark%2C_and_parts_adjacent%2C_etc%27_%2811013597895%29.jpg'::text),
  ('3f03f1d8-1255-45d1-8fc6-38435a1cce9b'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/2016_photos_-_IMG_5379_%2837924436521%29.jpg/960px-2016_photos_-_IMG_5379_%2837924436521%29.jpg'::text),
  ('7884431c-8829-4dab-b7d3-75104881073b'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/1000282_II_Star_PARK_OF_HAM_HOUSE%2C_South_Terrace_London_20250616_0002.jpg/960px-1000282_II_Star_PARK_OF_HAM_HOUSE%2C_South_Terrace_London_20250616_0002.jpg'::text),
  ('5fb8e370-3745-4404-9b17-d1536f26b44a'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Architectural_plans_for_Hampton_Court_Palace%2C_England_%285139859395%29.jpg/960px-Architectural_plans_for_Hampton_Court_Palace%2C_England_%285139859395%29.jpg'::text),
  ('f7303fe5-0c53-4bad-82ab-da564e9fabf3'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/%28Late%29_Kew_Palace%2C_objectnr_A_58092.jpg/960px-%28Late%29_Kew_Palace%2C_objectnr_A_58092.jpg'::text),
  ('91f3e0f9-e507-4322-abac-a9f41592b349'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Buildings_on_The_Outer_Circle%2C_viewed_from_the_end_of_the_path_-_geograph.org.uk_-_2564440.jpg/960px-Buildings_on_The_Outer_Circle%2C_viewed_from_the_end_of_the_path_-_geograph.org.uk_-_2564440.jpg'::text),
  ('19ce63a0-22a3-43af-b9f7-326e9ddf56c3'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/1911_Coronation_Aerial_Posting_Box.jpg/960px-1911_Coronation_Aerial_Posting_Box.jpg'::text),
  ('e1c49530-67dc-40f6-bb56-0e84e1791fa2'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/007SFEC_TOWER_OF_LONDON-200705.JPG/960px-007SFEC_TOWER_OF_LONDON-200705.JPG'::text),
  ('fe90572e-1324-4150-b616-5a46d4121269'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/2019-09-20_Stone_at_Westminster_Abbey.jpg/960px-2019-09-20_Stone_at_Westminster_Abbey.jpg'::text),
  ('eda4e334-cd8f-417b-8b42-e35d27cd0fb1'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/19960527_17_Victoria_Embankment_Gardens.jpg/960px-19960527_17_Victoria_Embankment_Gardens.jpg'::text)
)
update public.activities as activity
set wikimedia_image_url = image_updates.wikimedia_image_url, updated_at = now()
from image_updates
where activity.activity_id = image_updates.activity_id
  and nullif(btrim(activity.wikimedia_image_url), '') is null;
