-- Generated by scripts/audit-activity-suitability.js
-- Archive only high-confidence unsuitable venues.
-- Other potentially relevant places remain available for editorial review.
with unsuitable_listings (activity_id, archive_reason) as (
  values
    ('81242145-5c2a-4712-82ba-3feaf076043f'::uuid, 'Explicit greasy-spoon cafe is outside the family cafe directory'::text)
)
update public.activities as activity
set archive = true,
    public_listing_status = 'archived',
    archive_reason = unsuitable_listings.archive_reason,
    archived_at = coalesce(activity.archived_at, now()),
    updated_at = now()
from unsuitable_listings
where activity.activity_id = unsuitable_listings.activity_id
  and coalesce(activity.archive, false) = false
  and activity.public_listing_status = 'published';
