-- Generated by scripts/enrich-activity-provider-links.js
-- Uses listing metadata to find independent organiser websites for Happity,
-- Fever, and Eventbrite records. Listing URLs are retained separately.
with updates (activity_id, website, organiser_website) as (
  values
    ($$2b8af305-8085-4e32-bf1b-d1679566ccbf$$::uuid, $$https://www.timeout.com/london/attractions/highgate-wood$$::text, null::text)
)
update public.activities as activity
set
  website = coalesce(updates.website, activity.website),
  organiser_website = coalesce(updates.organiser_website, activity.organiser_website),
  updated_at = now()
from updates
where activity.activity_id = updates.activity_id;
