-- Generated by scripts/populate-wikimedia-images.js
-- Wikimedia Commons matches: 13 of 321 park/outdoor activities searched.

with image_updates (activity_id, wikimedia_image_url) as (
  values
    ('1ec9bcd9-36df-4069-9315-550ba71d6dc6'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Anzac_Gallipoli_War_Memorial%2C_Battersea_Park_-_London..jpg/640px-Anzac_Gallipoli_War_Memorial%2C_Battersea_Park_-_London..jpg'::text),
    ('3d4a6938-a89b-47c6-8c5a-dfb43e1dd431'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Across_Clissold_Park_-_geograph.org.uk_-_7957694.jpg/640px-Across_Clissold_Park_-_geograph.org.uk_-_7957694.jpg'::text),
    ('51cb016a-7832-402b-9d3b-2a4bead9dd59'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Archbishop%27s_Park_-_geograph.org.uk_-_2721029.jpg/640px-Archbishop%27s_Park_-_geograph.org.uk_-_2721029.jpg'::text),
    ('52d65a4f-d98a-4584-b750-eee6cc095735'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Across_Clissold_Park_-_geograph.org.uk_-_7957694.jpg/640px-Across_Clissold_Park_-_geograph.org.uk_-_7957694.jpg'::text),
    ('77a2e530-62b9-4db7-9de1-c500a2fbdba4'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/f/fb/Across_Brockwell_Park_-_geograph.org.uk_-_4975837.jpg'::text),
    ('7ca1c138-6330-4505-b08d-78802d79cd8e'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/2005-03-31_-_United_Kingdom_-_England_-_London_-_Greenwich_-_Greenwich_Park%2C_Queen%27s_House%2C_Old_Roya_4887770180.jpg/640px-2005-03-31_-_United_Kingdom_-_England_-_London_-_Greenwich_-_Greenwich_Park%2C_Queen%27s_House%2C_Old_Roya_4887770180.jpg'::text),
    ('86559486-3574-4a7e-993b-40db86f5decc'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Ancient_Tree_near_Pymms%27_Brook_with_Viaduct%2C_Arnos_Park_-_geograph.org.uk_-_6914839.jpg/640px-Ancient_Tree_near_Pymms%27_Brook_with_Viaduct%2C_Arnos_Park_-_geograph.org.uk_-_6914839.jpg'::text),
    ('abca40f1-9c9c-418f-9aa0-42d154f9a823'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Bandstand%2C_Elthorne_Park_-_geograph.org.uk_-_4973421.jpg/640px-Bandstand%2C_Elthorne_Park_-_geograph.org.uk_-_4973421.jpg'::text),
    ('cdf694ed-1c14-4f89-8118-6fa59ca102bb'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Across_Clissold_Park_-_geograph.org.uk_-_7957694.jpg/640px-Across_Clissold_Park_-_geograph.org.uk_-_7957694.jpg'::text),
    ('d136fbd0-f54c-45d6-b7b5-b5e1205e0463'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/A_Game_in_Finsbury_Park_-_geograph.org.uk_-_4446972.jpg/640px-A_Game_in_Finsbury_Park_-_geograph.org.uk_-_4446972.jpg'::text),
    ('e82778b1-f2d7-4fb1-b184-a6c19b1defd1'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/3/33/A_view_of_the_City_from_a_manmade_hill%2C_Burgess_Park_-_geograph.org.uk_-_3899206.jpg'::text),
    ('f0c8c762-aed8-492e-9029-d792e8d04fb1'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Barnsbury_Wood_1.JPG/640px-Barnsbury_Wood_1.JPG'::text),
    ('fe4ffb50-2f82-4517-a2f2-2c1ac59474f6'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Across_Clissold_Park_-_geograph.org.uk_-_7957694.jpg/640px-Across_Clissold_Park_-_geograph.org.uk_-_7957694.jpg'::text)
)
update public.activities as activity
set wikimedia_image_url = image_updates.wikimedia_image_url,
    updated_at = now()
from image_updates
where activity.activity_id = image_updates.activity_id
  and nullif(btrim(activity.wikimedia_image_url), '') is null;
