-- Generated by scripts/apply-activity-data-quality.js
-- Shared non-destructive quality rules for all Tiny Outings importers.

update public.activities
set
  activity_name = nullif(regexp_replace(trim(activity_name), '[[:cntrl:]]+', ' ', 'g'), ''),
  address = nullif(regexp_replace(trim(address), '[[:cntrl:]]+', ' ', 'g'), ''),
  description = nullif(regexp_replace(trim(description), '[[:cntrl:]]+', ' ', 'g'), ''),
  cost = nullif(regexp_replace(trim(cost), '[[:cntrl:]]+', ' ', 'g'), ''),
  website = nullif(trim(website), ''),
  organiser_website = nullif(trim(organiser_website), ''),
  source_url = nullif(trim(source_url), ''),
  image_url = nullif(trim(image_url), ''),
  updated_at = now()
where activity_name ~ '[[:cntrl:]]'
   or address ~ '[[:cntrl:]]'
   or description ~ '[[:cntrl:]]'
   or cost ~ '[[:cntrl:] ]$'
   or website ~ '^\s+$'
   or organiser_website ~ '^\s+$'
   or source_url ~ '^\s+$'
   or image_url ~ '^\s+$';

-- Restore source grouping from the stable importer provenance. This keeps the
-- Plan filter and card tag consistent even when a legacy importer used "other".
update public.activities
set data_source = case
  when source_name = 'Happity' then 'Happity'
  when source_name ilike 'Google Places%' then 'Google Places'
  when source_name ilike 'Better Start%' then 'Better Start for Life'
  when source_name ilike 'Eventbrite%' then 'Eventbrite'
  when source_name ilike 'Fever%' then 'Fever'
  when source_name ilike 'Loopla%' then 'Loopla'
  when source_name ilike 'Time Out%' then 'Time Out'
  when source_name ilike 'Museums London%' then 'Museums London'
  when source_name ilike '%directory%' then 'Local directory'
  else coalesce(nullif(data_source, ''), 'Other')
end,
updated_at = now()
where source_name is not null;

-- A listing website and organiser website serve different purposes. Keep the
-- organiser link only when it points somewhere different, so cards never show
-- duplicate buttons for the same destination.
update public.activities
set organiser_website = null,
    updated_at = now()
where nullif(trim(website), '') is not null
  and nullif(trim(organiser_website), '') is not null
  and regexp_replace(regexp_replace(regexp_replace(lower(trim(website)), '^https?://(www\.)?', ''), '[?#].*$', ''), '/+$', '')
      = regexp_replace(regexp_replace(regexp_replace(lower(trim(organiser_website)), '^https?://(www\.)?', ''), '[?#].*$', ''), '/+$', '');
