-- Generated by scripts/populate-wikimedia-images.js
-- Wikimedia Commons matches: 15 of 336 park/outdoor activities searched.

with image_updates (activity_id, wikimedia_image_url) as (
  values
    ('1cc47097-3f44-40a3-a75b-ed0def47aa81'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Avondale_Park_pond.JPG/1280px-Avondale_Park_pond.JPG'::text),
    ('23e7e9e8-48d9-4aa2-96ad-4cd63f8e4739'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/f/f6/Bat_boxes%2C_Duncan_Terrace_Gardens_-_geograph.org.uk_-_2917418.jpg'::text),
    ('3b2d13bc-8b2b-4595-8ed0-d29c95f07f6c'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Boundary_wall%2C_Freightliners_Farm%2C_Sheringham_Road%2C_London_N7_-_geograph.org.uk_-_1749452.jpg/1280px-Boundary_wall%2C_Freightliners_Farm%2C_Sheringham_Road%2C_London_N7_-_geograph.org.uk_-_1749452.jpg'::text),
    ('41469d8e-3836-43f6-bb4e-1a35e7aecad5'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/A_poorly_drained_part_of_Dulwich_Park_-_geograph.org.uk_-_3855376.jpg/1280px-A_poorly_drained_part_of_Dulwich_Park_-_geograph.org.uk_-_3855376.jpg'::text),
    ('6db05b55-6ce9-443c-b962-99c2fe9158ea'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Chase_Lane_Park_20191028_142634_%2848974938847%29.jpg/1280px-Chase_Lane_Park_20191028_142634_%2848974938847%29.jpg'::text),
    ('72a89040-f9d6-4628-a4dd-5167a5689a8c'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Bandstand%2C_Elthorne_Park_-_geograph.org.uk_-_4973421.jpg/1280px-Bandstand%2C_Elthorne_Park_-_geograph.org.uk_-_4973421.jpg'::text),
    ('7fd6d9ad-5e25-44a5-aebc-79e14359ffb9'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/%22Golders_Hill_Girl%22%2C_Golders_Hill_Park_-_geograph.org.uk_-_5961819.jpg/1280px-%22Golders_Hill_Girl%22%2C_Golders_Hill_Park_-_geograph.org.uk_-_5961819.jpg'::text),
    ('9fd4a77d-1c57-4d0a-8c68-95d22ce44f7a'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/3/38/Bloomsbury%2C_Coram%27s_Fields_-_geograph.org.uk_-_3009823.jpg'::text),
    ('a8c6fa7c-4623-488e-9a26-b52f2c7d220d'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/c/c4/Across_Clissold_Park_-_geograph.org.uk_-_7957694.jpg'::text),
    ('b69677b2-40ea-4ff2-9b44-e4994a3a282d'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Compton_Terrace_Gardens_01.jpg/1280px-Compton_Terrace_Gardens_01.jpg'::text),
    ('c359c2f8-a5f6-46a7-bc75-398624de982b'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/%22Golders_Hill_Girl%22%2C_Golders_Hill_Park_-_geograph.org.uk_-_5961819.jpg/1280px-%22Golders_Hill_Girl%22%2C_Golders_Hill_Park_-_geograph.org.uk_-_5961819.jpg'::text),
    ('d06083d8-db8c-42a3-a43c-69e6e998259e'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Gandhi_Chaplin_Memorial_Garden%2C_Canning_Town_01.jpg/1280px-Gandhi_Chaplin_Memorial_Garden%2C_Canning_Town_01.jpg'::text),
    ('dcb2282e-64ce-48b4-ba8b-7faebedb684d'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Approaching_the_caf%C3%A9%2C_Crystal_Palace_Park_-_geograph.org.uk_-_7219104.jpg/1280px-Approaching_the_caf%C3%A9%2C_Crystal_Palace_Park_-_geograph.org.uk_-_7219104.jpg'::text),
    ('e487f2c0-4ab8-44ef-8210-f02c27431170'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Cundy_Park_20171014_165128_%2849450527018%29.jpg/1280px-Cundy_Park_20171014_165128_%2849450527018%29.jpg'::text),
    ('f731c6f4-e0d7-4c50-a690-76bacdb6d442'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Gillespie_Park_1.JPG/1280px-Gillespie_Park_1.JPG'::text)
)
update public.activities as activity
set wikimedia_image_url = image_updates.wikimedia_image_url,
    updated_at = now()
from image_updates
where activity.activity_id = image_updates.activity_id
  and nullif(btrim(activity.wikimedia_image_url), '') is null;
