-- Generated by scripts/populate-wikimedia-images.js
-- Wikimedia Commons matches: 7 of 308 park/outdoor activities searched.

with image_updates (activity_id, wikimedia_image_url) as (
  values
    ('2b8af305-8085-4e32-bf1b-d1679566ccbf'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Autumnal_scene%2C_Highgate_Wood_-_geograph.org.uk_-_4711452.jpg/960px-Autumnal_scene%2C_Highgate_Wood_-_geograph.org.uk_-_4711452.jpg'::text),
    ('30b2e789-57e8-4e79-8737-547e607c12c5'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Autumn_colour_on_Highbury_Fields_-_geograph.org.uk_-_5971192.jpg/960px-Autumn_colour_on_Highbury_Fields_-_geograph.org.uk_-_5971192.jpg'::text),
    ('7fb6c781-a93e-49df-9386-60e57e9ca5fe'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Centenary_Walk_alongside_Highams_Park_lake_-_geograph.org.uk_-_4415075.jpg/960px-Centenary_Walk_alongside_Highams_Park_lake_-_geograph.org.uk_-_4415075.jpg'::text),
    ('8b95cb0b-229a-40d1-8847-e1525a80988a'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/7/7e/All-weather_pitch%2C_Haggerston_Park_E2_-_geograph.org.uk_-_1600111.jpg'::text),
    ('b4732f7c-de32-41ba-93e7-c9d96b3ace63'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/W.W._JACOBS_-_15_Gloucester_Gate_%28Albany_Street_frontage%29_Regent%27s_Park_London_NW1_4HG.jpg/960px-W.W._JACOBS_-_15_Gloucester_Gate_%28Albany_Street_frontage%29_Regent%27s_Park_London_NW1_4HG.jpg'::text),
    ('c9226e47-8fbe-4aeb-aea1-d02f34c05826'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Autumnal_scene%2C_Highgate_Wood_-_geograph.org.uk_-_4711452.jpg/960px-Autumnal_scene%2C_Highgate_Wood_-_geograph.org.uk_-_4711452.jpg'::text),
    ('e7132d4b-83e7-4e0d-bf8c-113c59eab09f'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Dismantling_of_Overhead_Cables%2C_Oct_2008%2C_Hackney_Marshes.jpg/960px-Dismantling_of_Overhead_Cables%2C_Oct_2008%2C_Hackney_Marshes.jpg'::text)
)
update public.activities as activity
set wikimedia_image_url = image_updates.wikimedia_image_url,
    updated_at = now()
from image_updates
where activity.activity_id = image_updates.activity_id
  and nullif(btrim(activity.wikimedia_image_url), '') is null;
