insert into public.activities (
  activity_name,
  address,
  postcode,
  lat,
  long,
  category,
  start_time,
  end_time,
  google_link,
  website,
  child_friendly_score,
  app_rating,
  number_of_reviews,
  age_suitability,
  borough,
  days_of_week,
  recurrence_rule,
  schedule_notes,
  description,
  cost,
  booking_required,
  source_name,
  source_url,
  image_url,
  image_source_url,
  activity_date,
  available_dates,
  availability_start_date,
  availability_end_date,
  available_days_of_week,
  availability_type,
  availability_notes,
  public_listing_status
)
values
(
  $$Tumble Tots - 2-3 Year Olds$$,
  $$Wanstead House Community Association, London E11$$,
  $$E11$$,
  null,
  null,
  $$family activity$$,
  $$09:30$$,
  $$10:15$$,
  null,
  $$https://www.happity.co.uk/waltham-forest/baby-toddler-classes#tumble-tots-2-3-year-olds-wanstead-house-wed-0930$$,
  null,
  null,
  0,
  $$2 years - 3 years$$,
  $$Waltham Forest$$,
  array[$$Wednesday$$],
  $$FREQ=WEEKLY;BYDAY=WE$$,
  $$Wednesday listing on Happity; term time only.$$
  ,
  $$Toddler movement class with active play and confidence-building exercises; check Happity for current term dates.$$
  ,
  $$Check Happity$$,
  true,
  $$Happity$$,
  $$https://www.happity.co.uk/waltham-forest/baby-toddler-classes#tumble-tots-2-3-year-olds-wanstead-house-wed-0930$$,
  null,
  $$https://www.happity.co.uk/waltham-forest/baby-toddler-classes#tumble-tots-2-3-year-olds-wanstead-house-wed-0930$$,
  null,
  '{}',
  null,
  null,
  array[$$Wednesday$$],
  $$weekly$$,
  $$Imported from Happity Waltham Forest listings. Verify live schedule and booking before travelling.$$
  ,
  $$published$$
),
(
  $$Bongalong - Under Ones Trial Session$$,
  $$Highams Park Baptist Church, London E4$$,
  $$E4$$,
  null,
  null,
  $$family activity$$,
  $$11:00$$,
  $$11:45$$,
  null,
  $$https://www.happity.co.uk/waltham-forest/baby-toddler-classes#bongalong-under-ones-highams-park-wed-1100$$,
  null,
  null,
  0,
  $$0 months - 12 months$$,
  $$Waltham Forest$$,
  array[$$Wednesday$$],
  $$FREQ=WEEKLY;BYDAY=WE$$,
  $$Wednesday listing on Happity; selected dates.$$
  ,
  $$Music and movement session for babies under one, with a trial option shown on Happity.$$
  ,
  $$£11.00$$,
  true,
  $$Happity$$,
  $$https://www.happity.co.uk/waltham-forest/baby-toddler-classes#bongalong-under-ones-highams-park-wed-1100$$,
  null,
  $$https://www.happity.co.uk/waltham-forest/baby-toddler-classes#bongalong-under-ones-highams-park-wed-1100$$,
  null,
  '{}',
  null,
  null,
  array[$$Wednesday$$],
  $$weekly$$,
  $$Imported from Happity Waltham Forest listings. Verify live schedule and booking before travelling.$$
  ,
  $$published$$
),
(
  $$Mother & More - Baby Massage & Baby Yoga Stage 1$$,
  $$Pause, London E10$$,
  $$E10$$,
  null,
  null,
  $$baby yoga$$,
  $$13:00$$,
  $$13:45$$,
  null,
  $$https://www.happity.co.uk/waltham-forest/baby-toddler-classes#mother-and-more-stage-1-pause-wed-1300$$,
  null,
  null,
  0,
  $$1 month - 9 months$$,
  $$Waltham Forest$$,
  array[$$Wednesday$$],
  $$FREQ=WEEKLY;BYDAY=WE$$,
  $$Wednesday listing on Happity; fixed course dates.$$
  ,
  $$Parent-and-baby course combining baby massage and gentle baby yoga for younger babies.$$
  ,
  $$£114.00$$,
  true,
  $$Happity$$,
  $$https://www.happity.co.uk/waltham-forest/baby-toddler-classes#mother-and-more-stage-1-pause-wed-1300$$,
  null,
  $$https://www.happity.co.uk/waltham-forest/baby-toddler-classes#mother-and-more-stage-1-pause-wed-1300$$,
  null,
  '{}',
  null,
  null,
  array[$$Wednesday$$],
  $$weekly$$,
  $$Imported from Happity Waltham Forest listings. Verify live schedule and booking before travelling.$$
  ,
  $$published$$
),
(
  $$The Castle Play Space - Stay and Play$$,
  $$The Castle Play Space, London E11$$,
  $$E11$$,
  null,
  null,
  $$baby stay and play$$,
  $$09:30$$,
  $$11:00$$,
  null,
  $$https://www.happity.co.uk/waltham-forest/baby-toddler-classes#castle-play-space-stay-and-play-wed-0930$$,
  null,
  null,
  0,
  $$6 months - 4 years$$,
  $$Waltham Forest$$,
  array[$$Wednesday$$],
  $$FREQ=WEEKLY;BYDAY=WE$$,
  $$Wednesday listing on Happity; event listing.$$
  ,
  $$Stay-and-play session for babies and preschoolers in a dedicated early years play space.$$
  ,
  $$£3.00 - £10.00$$,
  true,
  $$Happity$$,
  $$https://www.happity.co.uk/waltham-forest/baby-toddler-classes#castle-play-space-stay-and-play-wed-0930$$,
  null,
  $$https://www.happity.co.uk/waltham-forest/baby-toddler-classes#castle-play-space-stay-and-play-wed-0930$$,
  null,
  '{}',
  null,
  null,
  array[$$Wednesday$$],
  $$weekly$$,
  $$Imported from Happity Waltham Forest listings. Verify live schedule and booking before travelling.$$
  ,
  $$published$$
),
(
  $$Mums Art Club$$,
  $$The Quaker Meeting House, London E17$$,
  $$E17$$,
  null,
  null,
  $$family activity$$,
  $$10:00$$,
  $$11:30$$,
  null,
  $$https://www.happity.co.uk/waltham-forest/baby-toddler-classes#mums-art-club-quaker-meeting-house-wed-1000$$,
  null,
  null,
  0,
  $$Antenatal to 12 months$$,
  $$Waltham Forest$$,
  array[$$Wednesday$$],
  $$FREQ=WEEKLY;BYDAY=WE$$,
  $$Wednesday listing on Happity; selected dates.$$
  ,
  $$Creative session designed for parents with very young babies, with art activities and social time.$$
  ,
  $$£22.00 - £54.00$$,
  true,
  $$Happity$$,
  $$https://www.happity.co.uk/waltham-forest/baby-toddler-classes#mums-art-club-quaker-meeting-house-wed-1000$$,
  null,
  $$https://www.happity.co.uk/waltham-forest/baby-toddler-classes#mums-art-club-quaker-meeting-house-wed-1000$$,
  null,
  '{}',
  null,
  null,
  array[$$Wednesday$$],
  $$weekly$$,
  $$Imported from Happity Waltham Forest listings. Verify live schedule and booking before travelling.$$
  ,
  $$published$$
),
(
  $$Thula Mama - Singing With Babies$$,
  $$Yonder Studio E17, London E17$$,
  $$E17$$,
  null,
  null,
  $$family activity$$,
  $$10:00$$,
  $$10:45$$,
  null,
  $$https://www.happity.co.uk/waltham-forest/baby-toddler-classes#thula-mama-yonder-studio-wed-1000$$,
  null,
  null,
  0,
  $$0 months - 12 months$$,
  $$Waltham Forest$$,
  array[$$Wednesday$$],
  $$FREQ=WEEKLY;BYDAY=WE$$,
  $$Wednesday listing on Happity; term time only.$$
  ,
  $$Singing group for parents and babies, focused on connection, songs and gentle social time.$$
  ,
  $$£12.00$$,
  true,
  $$Happity$$,
  $$https://www.happity.co.uk/waltham-forest/baby-toddler-classes#thula-mama-yonder-studio-wed-1000$$,
  null,
  $$https://www.happity.co.uk/waltham-forest/baby-toddler-classes#thula-mama-yonder-studio-wed-1000$$,
  null,
  '{}',
  null,
  null,
  array[$$Wednesday$$],
  $$weekly$$,
  $$Imported from Happity Waltham Forest listings. Verify live schedule and booking before travelling.$$
  ,
  $$published$$
),
(
  $$Sing and Sign - Stage Two$$,
  $$St Joseph's Roman Catholic Church Community Hall, London E10$$,
  $$E10$$,
  null,
  null,
  $$baby signing$$,
  $$10:15$$,
  $$11:00$$,
  null,
  $$https://www.happity.co.uk/waltham-forest/baby-toddler-classes#sing-and-sign-stage-two-st-josephs-wed-1015$$,
  null,
  null,
  0,
  $$14 months - 2 years$$,
  $$Waltham Forest$$,
  array[$$Wednesday$$],
  $$FREQ=WEEKLY;BYDAY=WE$$,
  $$Wednesday listing on Happity; term time only.$$
  ,
  $$Baby signing music class for older babies and young toddlers.$$
  ,
  $$£13.00$$,
  true,
  $$Happity$$,
  $$https://www.happity.co.uk/waltham-forest/baby-toddler-classes#sing-and-sign-stage-two-st-josephs-wed-1015$$,
  null,
  $$https://www.happity.co.uk/waltham-forest/baby-toddler-classes#sing-and-sign-stage-two-st-josephs-wed-1015$$,
  null,
  '{}',
  null,
  null,
  array[$$Wednesday$$],
  $$weekly$$,
  $$Imported from Happity Waltham Forest listings. Verify live schedule and booking before travelling.$$
  ,
  $$published$$
),
(
  $$Walthamstow Toy Library - Sensory Room Session$$,
  $$Walthamstow Toy Library, London E17$$,
  $$E17$$,
  null,
  null,
  $$sensory play$$,
  $$09:30$$,
  $$10:15$$,
  null,
  $$https://www.happity.co.uk/waltham-forest/baby-toddler-classes#walthamstow-toy-library-sensory-room-wed-0930$$,
  null,
  null,
  0,
  $$0 months - 5 years$$,
  $$Waltham Forest$$,
  array[$$Wednesday$$],
  $$FREQ=WEEKLY;BYDAY=WE$$,
  $$Wednesday listing on Happity; all year.$$
  ,
  $$Sensory room session for babies, toddlers and preschoolers at Walthamstow Toy Library.$$
  ,
  $$£2.00 - £5.00$$,
  true,
  $$Happity$$,
  $$https://www.happity.co.uk/waltham-forest/baby-toddler-classes#walthamstow-toy-library-sensory-room-wed-0930$$,
  null,
  $$https://www.happity.co.uk/waltham-forest/baby-toddler-classes#walthamstow-toy-library-sensory-room-wed-0930$$,
  null,
  '{}',
  null,
  null,
  array[$$Wednesday$$],
  $$weekly$$,
  $$Imported from Happity Waltham Forest listings. Verify live schedule and booking before travelling.$$
  ,
  $$published$$
),
(
  $$Zip Zap - Toddlers$$,
  $$St Mary's Church Stoke Newington, London N16$$,
  $$N16$$,
  null,
  null,
  $$sensory play$$,
  $$10:00$$,
  $$10:45$$,
  null,
  $$https://www.happity.co.uk/hackney/baby-toddler-classes#zip-zap-toddlers-st-marys-stoke-newington-mon-1000$$,
  null,
  null,
  0,
  $$12 months - 4 years$$,
  $$Hackney$$,
  array[$$Monday$$],
  $$FREQ=WEEKLY;BYDAY=MO$$,
  $$Monday listing on Happity; term time only.$$
  ,
  $$Music, movement and sensory-style class for toddlers and preschoolers.$$
  ,
  $$£11.00 - £112.00$$,
  true,
  $$Happity$$,
  $$https://www.happity.co.uk/hackney/baby-toddler-classes#zip-zap-toddlers-st-marys-stoke-newington-mon-1000$$,
  null,
  $$https://www.happity.co.uk/hackney/baby-toddler-classes#zip-zap-toddlers-st-marys-stoke-newington-mon-1000$$,
  null,
  '{}',
  null,
  null,
  array[$$Monday$$],
  $$weekly$$,
  $$Imported from Happity Hackney listings. Verify live schedule and booking before travelling.$$
  ,
  $$published$$
),
(
  $$Monkey Music - Rock 'n' Roll$$,
  $$St Mary's Church, London N1$$,
  $$N1$$,
  null,
  null,
  $$family activity$$,
  $$11:40$$,
  $$12:10$$,
  null,
  $$https://www.happity.co.uk/hackney/baby-toddler-classes#monkey-music-rock-n-roll-st-marys-mon-1140$$,
  null,
  null,
  0,
  $$3 months - 12 months$$,
  $$Hackney$$,
  array[$$Monday$$],
  $$FREQ=WEEKLY;BYDAY=MO$$,
  $$Monday listing on Happity; term time only.$$
  ,
  $$Baby music class for very young babies, with songs, rhythm and parent participation.$$
  ,
  $$£12.75$$,
  true,
  $$Happity$$,
  $$https://www.happity.co.uk/hackney/baby-toddler-classes#monkey-music-rock-n-roll-st-marys-mon-1140$$,
  null,
  $$https://www.happity.co.uk/hackney/baby-toddler-classes#monkey-music-rock-n-roll-st-marys-mon-1140$$,
  null,
  '{}',
  null,
  null,
  array[$$Monday$$],
  $$weekly$$,
  $$Imported from Happity Hackney listings. Verify live schedule and booking before travelling.$$
  ,
  $$published$$
),
(
  $$Little Movers Gym - Open Gym$$,
  $$Gracepoint, London N1$$,
  $$N1$$,
  null,
  null,
  $$soft play$$,
  $$09:30$$,
  $$10:30$$,
  null,
  $$https://www.happity.co.uk/hackney/baby-toddler-classes#little-movers-gym-open-gym-gracepoint-mon-0930$$,
  null,
  null,
  0,
  $$6 months - 12 years$$,
  $$Hackney$$,
  array[$$Monday$$],
  $$FREQ=WEEKLY;BYDAY=MO$$,
  $$Monday listing on Happity; selected dates.$$
  ,
  $$Open gym session for babies, toddlers and older children, with active indoor play.$$
  ,
  $$£10.00$$,
  true,
  $$Happity$$,
  $$https://www.happity.co.uk/hackney/baby-toddler-classes#little-movers-gym-open-gym-gracepoint-mon-0930$$,
  null,
  $$https://www.happity.co.uk/hackney/baby-toddler-classes#little-movers-gym-open-gym-gracepoint-mon-0930$$,
  null,
  '{}',
  null,
  null,
  array[$$Monday$$],
  $$weekly$$,
  $$Imported from Happity Hackney listings. Verify live schedule and booking before travelling.$$
  ,
  $$published$$
),
(
  $$Tick Tock Music$$,
  $$St Stephen's, Canonbury, London N1$$,
  $$N1$$,
  null,
  null,
  $$family activity$$,
  $$09:45$$,
  $$10:30$$,
  null,
  $$https://www.happity.co.uk/hackney/baby-toddler-classes#tick-tock-music-st-stephens-canonbury-mon-0945$$,
  null,
  null,
  0,
  $$6 months - 5 years$$,
  $$Hackney$$,
  array[$$Monday$$],
  $$FREQ=WEEKLY;BYDAY=MO$$,
  $$Monday listing on Happity; term time only.$$
  ,
  $$Music session for babies, toddlers and preschoolers with songs and group participation.$$
  ,
  $$£12.00 - £48.00$$,
  true,
  $$Happity$$,
  $$https://www.happity.co.uk/hackney/baby-toddler-classes#tick-tock-music-st-stephens-canonbury-mon-0945$$,
  null,
  $$https://www.happity.co.uk/hackney/baby-toddler-classes#tick-tock-music-st-stephens-canonbury-mon-0945$$,
  null,
  '{}',
  null,
  null,
  array[$$Monday$$],
  $$weekly$$,
  $$Imported from Happity Hackney listings. Verify live schedule and booking before travelling.$$
  ,
  $$published$$
),
(
  $$Lisa Gilbert Academy - Pre-school Acro/Gymnastics$$,
  $$Oxford House Bethnal Green, London E2$$,
  $$E2$$,
  null,
  null,
  $$family activity$$,
  $$09:45$$,
  $$10:30$$,
  null,
  $$https://www.happity.co.uk/hackney/baby-toddler-classes#lisa-gilbert-preschool-acro-gymnastics-mon-0945$$,
  null,
  null,
  0,
  $$2 years - 5 years$$,
  $$Hackney$$,
  array[$$Monday$$],
  $$FREQ=WEEKLY;BYDAY=MO$$,
  $$Monday listing on Happity; term time only.$$
  ,
  $$Pre-school acro and gymnastics class for confident movers and energetic preschoolers.$$
  ,
  $$£13.00 - £13.50$$,
  true,
  $$Happity$$,
  $$https://www.happity.co.uk/hackney/baby-toddler-classes#lisa-gilbert-preschool-acro-gymnastics-mon-0945$$,
  null,
  $$https://www.happity.co.uk/hackney/baby-toddler-classes#lisa-gilbert-preschool-acro-gymnastics-mon-0945$$,
  null,
  '{}',
  null,
  null,
  array[$$Monday$$],
  $$weekly$$,
  $$Imported from Happity Hackney listings. Verify live schedule and booking before travelling.$$
  ,
  $$published$$
),
(
  $$Little Boo Stories - Mini Boo Interactive Stories$$,
  $$Christ Church Highbury, London N5$$,
  $$N5$$,
  null,
  null,
  $$story time$$,
  $$10:00$$,
  $$10:45$$,
  null,
  $$https://www.happity.co.uk/hackney/baby-toddler-classes#little-boo-stories-mini-boo-christ-church-highbury-mon-1000$$,
  null,
  null,
  0,
  $$19 months - 5 years$$,
  $$Hackney$$,
  array[$$Monday$$],
  $$FREQ=WEEKLY;BYDAY=MO$$,
  $$Monday listing on Happity; term time only.$$
  ,
  $$Interactive storytelling class for toddlers and preschoolers, with imaginative sensory elements.$$
  ,
  $$£9.00 - £40.00$$,
  true,
  $$Happity$$,
  $$https://www.happity.co.uk/hackney/baby-toddler-classes#little-boo-stories-mini-boo-christ-church-highbury-mon-1000$$,
  null,
  $$https://www.happity.co.uk/hackney/baby-toddler-classes#little-boo-stories-mini-boo-christ-church-highbury-mon-1000$$,
  null,
  '{}',
  null,
  null,
  array[$$Monday$$],
  $$weekly$$,
  $$Imported from Happity Hackney listings. Verify live schedule and booking before travelling.$$
  ,
  $$published$$
),
(
  $$Sing and Sign - Stage 1 Baby Signing Music Class$$,
  $$St Mary's Neighbourhood Centre, London N1$$,
  $$N1$$,
  null,
  null,
  $$baby signing$$,
  $$10:00$$,
  $$10:40$$,
  null,
  $$https://www.happity.co.uk/hackney/baby-toddler-classes#sing-and-sign-stage-1-st-marys-neighbourhood-mon-1000$$,
  null,
  null,
  0,
  $$6 months - 14 months$$,
  $$Hackney$$,
  array[$$Monday$$],
  $$FREQ=WEEKLY;BYDAY=MO$$,
  $$Monday listing on Happity; term time only.$$
  ,
  $$Baby signing music class for babies aged around six to fourteen months.$$
  ,
  $$£160.00$$,
  true,
  $$Happity$$,
  $$https://www.happity.co.uk/hackney/baby-toddler-classes#sing-and-sign-stage-1-st-marys-neighbourhood-mon-1000$$,
  null,
  $$https://www.happity.co.uk/hackney/baby-toddler-classes#sing-and-sign-stage-1-st-marys-neighbourhood-mon-1000$$,
  null,
  '{}',
  null,
  null,
  array[$$Monday$$],
  $$weekly$$,
  $$Imported from Happity Hackney listings. Verify live schedule and booking before travelling.$$
  ,
  $$published$$
),
(
  $$Minis$$,
  $$St Paul Old Ford Church, London E3$$,
  $$E3$$,
  null,
  null,
  $$family activity$$,
  $$10:00$$,
  $$11:15$$,
  null,
  $$https://www.happity.co.uk/hackney/baby-toddler-classes#minis-st-paul-old-ford-mon-1000$$,
  null,
  null,
  0,
  $$0 months - 4 years$$,
  $$Hackney$$,
  array[$$Monday$$],
  $$FREQ=WEEKLY;BYDAY=MO$$,
  $$Monday listing on Happity; selected dates.$$
  ,
  $$Creative baby and toddler session with arts-and-crafts style activities for families.$$
  ,
  $$£8.50 - £34.00$$,
  true,
  $$Happity$$,
  $$https://www.happity.co.uk/hackney/baby-toddler-classes#minis-st-paul-old-ford-mon-1000$$,
  null,
  $$https://www.happity.co.uk/hackney/baby-toddler-classes#minis-st-paul-old-ford-mon-1000$$,
  null,
  '{}',
  null,
  null,
  array[$$Monday$$],
  $$weekly$$,
  $$Imported from Happity Hackney listings. Verify live schedule and booking before travelling.$$
  ,
  $$published$$
),
(
  $$Singing Mamas Newham$$,
  $$Cornerstone Cafe London, London E13$$,
  $$E13$$,
  null,
  null,
  $$family activity$$,
  $$10:00$$,
  $$11:30$$,
  null,
  $$https://www.happity.co.uk/newham/baby-toddler-classes#singing-mamas-newham-cornerstone-cafe-tue-1000$$,
  null,
  null,
  0,
  $$Antenatal to 12 months$$,
  $$Newham$$,
  array[$$Tuesday$$],
  $$FREQ=WEEKLY;BYDAY=TU$$,
  $$Tuesday listing on Happity; term time only.$$
  ,
  $$Community singing circle for expectant parents, mothers and babies.$$
  ,
  $$free - £9.00$$,
  true,
  $$Happity$$,
  $$https://www.happity.co.uk/newham/baby-toddler-classes#singing-mamas-newham-cornerstone-cafe-tue-1000$$,
  null,
  $$https://www.happity.co.uk/newham/baby-toddler-classes#singing-mamas-newham-cornerstone-cafe-tue-1000$$,
  null,
  '{}',
  null,
  null,
  array[$$Tuesday$$],
  $$weekly$$,
  $$Imported from Happity Newham listings. Verify live schedule and booking before travelling.$$
  ,
  $$published$$
),
(
  $$Mother & More - Baby Massage & Baby Yoga Stage 2$$,
  $$Bridgets ASL and Chobham Manor Community Centre, London E20$$,
  $$E20$$,
  null,
  null,
  $$baby yoga$$,
  $$12:15$$,
  $$13:00$$,
  null,
  $$https://www.happity.co.uk/newham/baby-toddler-classes#mother-and-more-stage-2-chobham-manor-tue-1215$$,
  null,
  null,
  0,
  $$3 months - 10 months$$,
  $$Newham$$,
  array[$$Tuesday$$],
  $$FREQ=WEEKLY;BYDAY=TU$$,
  $$Tuesday listing on Happity; fixed course dates.$$
  ,
  $$Baby massage and baby yoga course for slightly older babies.$$
  ,
  $$£114.00$$,
  true,
  $$Happity$$,
  $$https://www.happity.co.uk/newham/baby-toddler-classes#mother-and-more-stage-2-chobham-manor-tue-1215$$,
  null,
  $$https://www.happity.co.uk/newham/baby-toddler-classes#mother-and-more-stage-2-chobham-manor-tue-1215$$,
  null,
  '{}',
  null,
  null,
  array[$$Tuesday$$],
  $$weekly$$,
  $$Imported from Happity Newham listings. Verify live schedule and booking before travelling.$$
  ,
  $$published$$
),
(
  $$Baby Dance by Wee Movers$$,
  $$Good Shepherd Studios, London E11$$,
  $$E11$$,
  null,
  null,
  $$family activity$$,
  $$10:40$$,
  $$11:25$$,
  null,
  $$https://www.happity.co.uk/newham/baby-toddler-classes#baby-dance-wee-movers-good-shepherd-tue-1040$$,
  null,
  null,
  0,
  $$0 months - 12 months$$,
  $$Newham$$,
  array[$$Tuesday$$],
  $$FREQ=WEEKLY;BYDAY=TU$$,
  $$Tuesday listing on Happity; selected dates.$$
  ,
  $$Baby dance class for carers and babies, with gentle movement and music.$$
  ,
  $$£15.00$$,
  true,
  $$Happity$$,
  $$https://www.happity.co.uk/newham/baby-toddler-classes#baby-dance-wee-movers-good-shepherd-tue-1040$$,
  null,
  $$https://www.happity.co.uk/newham/baby-toddler-classes#baby-dance-wee-movers-good-shepherd-tue-1040$$,
  null,
  '{}',
  null,
  null,
  array[$$Tuesday$$],
  $$weekly$$,
  $$Imported from Happity Newham listings. Verify live schedule and booking before travelling.$$
  ,
  $$published$$
),
(
  $$Juniorstrikers - Baby Strikers Football$$,
  $$Victoria Park, London E9$$,
  $$E9$$,
  null,
  null,
  $$family activity$$,
  $$09:40$$,
  $$10:10$$,
  null,
  $$https://www.happity.co.uk/newham/baby-toddler-classes#juniorstrikers-baby-strikers-victoria-park-tue-0940$$,
  null,
  null,
  0,
  $$18 months - 2 years 6 months$$,
  $$Newham$$,
  array[$$Tuesday$$],
  $$FREQ=WEEKLY;BYDAY=TU$$,
  $$Tuesday listing on Happity; selected dates.$$
  ,
  $$Introductory toddler football class for early movers.$$
  ,
  $$free$$,
  true,
  $$Happity$$,
  $$https://www.happity.co.uk/newham/baby-toddler-classes#juniorstrikers-baby-strikers-victoria-park-tue-0940$$,
  null,
  $$https://www.happity.co.uk/newham/baby-toddler-classes#juniorstrikers-baby-strikers-victoria-park-tue-0940$$,
  null,
  '{}',
  null,
  null,
  array[$$Tuesday$$],
  $$weekly$$,
  $$Imported from Happity Newham listings. Verify live schedule and booking before travelling.$$
  ,
  $$published$$
),
(
  $$Boppin' Bunnies - Pre-school Music$$,
  $$The Royal Standard, London SE3$$,
  $$SE3$$,
  null,
  null,
  $$sensory play$$,
  $$09:45$$,
  $$10:20$$,
  null,
  $$https://www.happity.co.uk/newham/baby-toddler-classes#boppin-bunnies-preschool-music-royal-standard-tue-0945$$,
  null,
  null,
  0,
  $$18 months - 4 years$$,
  $$Newham$$,
  array[$$Tuesday$$],
  $$FREQ=WEEKLY;BYDAY=TU$$,
  $$Tuesday listing on Happity; term time only.$$
  ,
  $$Pre-school music session with songs and movement for toddlers.$$
  ,
  $$£11.00 - £50.00$$,
  true,
  $$Happity$$,
  $$https://www.happity.co.uk/newham/baby-toddler-classes#boppin-bunnies-preschool-music-royal-standard-tue-0945$$,
  null,
  $$https://www.happity.co.uk/newham/baby-toddler-classes#boppin-bunnies-preschool-music-royal-standard-tue-0945$$,
  null,
  '{}',
  null,
  null,
  array[$$Tuesday$$],
  $$weekly$$,
  $$Imported from Happity Newham listings. Verify live schedule and booking before travelling.$$
  ,
  $$published$$
),
(
  $$Monkey Music - Jiggety-Jig$$,
  $$St George in the East, London E1$$,
  $$E1$$,
  null,
  null,
  $$sensory play$$,
  $$09:45$$,
  $$10:15$$,
  null,
  $$https://www.happity.co.uk/newham/baby-toddler-classes#monkey-music-jiggety-jig-st-george-east-tue-0945$$,
  null,
  null,
  0,
  $$2 years - 3 years$$,
  $$Newham$$,
  array[$$Tuesday$$],
  $$FREQ=WEEKLY;BYDAY=TU$$,
  $$Tuesday listing on Happity; term time only.$$
  ,
  $$Music and movement class for toddlers, with rhythm games and parent participation.$$
  ,
  $$£12.00$$,
  true,
  $$Happity$$,
  $$https://www.happity.co.uk/newham/baby-toddler-classes#monkey-music-jiggety-jig-st-george-east-tue-0945$$,
  null,
  $$https://www.happity.co.uk/newham/baby-toddler-classes#monkey-music-jiggety-jig-st-george-east-tue-0945$$,
  null,
  '{}',
  null,
  null,
  array[$$Tuesday$$],
  $$weekly$$,
  $$Imported from Happity Newham listings. Verify live schedule and booking before travelling.$$
  ,
  $$published$$
),
(
  $$Blossom Babies - Blossom Toddler$$,
  $$Poplar Union, London E14$$,
  $$E14$$,
  null,
  null,
  $$sensory play$$,
  $$10:00$$,
  $$10:45$$,
  null,
  $$https://www.happity.co.uk/newham/baby-toddler-classes#blossom-babies-blossom-toddler-poplar-union-tue-1000$$,
  null,
  null,
  0,
  $$13 months - 3 years$$,
  $$Newham$$,
  array[$$Tuesday$$],
  $$FREQ=WEEKLY;BYDAY=TU$$,
  $$Tuesday listing on Happity; selected dates.$$
  ,
  $$Toddler sensory session for active crawlers and walkers.$$
  ,
  $$Check Happity$$,
  true,
  $$Happity$$,
  $$https://www.happity.co.uk/newham/baby-toddler-classes#blossom-babies-blossom-toddler-poplar-union-tue-1000$$,
  null,
  $$https://www.happity.co.uk/newham/baby-toddler-classes#blossom-babies-blossom-toddler-poplar-union-tue-1000$$,
  null,
  '{}',
  null,
  null,
  array[$$Tuesday$$],
  $$weekly$$,
  $$Imported from Happity Newham listings. Verify live schedule and booking before travelling.$$
  ,
  $$published$$
),
(
  $$Flying Sycamores Forest School - Good Shepherd Studios$$,
  $$Good Shepherd Studios, London E11$$,
  $$E11$$,
  null,
  null,
  $$family activity$$,
  $$10:00$$,
  $$11:00$$,
  null,
  $$https://www.happity.co.uk/newham/baby-toddler-classes#flying-sycamores-good-shepherd-tue-1000$$,
  null,
  null,
  0,
  $$5 months - 4 years$$,
  $$Newham$$,
  array[$$Tuesday$$],
  $$FREQ=WEEKLY;BYDAY=TU$$,
  $$Tuesday listing on Happity; fixed course dates.$$
  ,
  $$Outdoor-inspired forest school session for babies, toddlers and preschoolers.$$
  ,
  $$£6.00 - £60.00$$,
  true,
  $$Happity$$,
  $$https://www.happity.co.uk/newham/baby-toddler-classes#flying-sycamores-good-shepherd-tue-1000$$,
  null,
  $$https://www.happity.co.uk/newham/baby-toddler-classes#flying-sycamores-good-shepherd-tue-1000$$,
  null,
  '{}',
  null,
  null,
  array[$$Tuesday$$],
  $$weekly$$,
  $$Imported from Happity Newham listings. Verify live schedule and booking before travelling.$$
  ,
  $$published$$
),
(
  $$Mini Mozart Baby Class$$,
  $$St Mary's Church, London N1$$,
  $$N1$$,
  null,
  null,
  $$family activity$$,
  $$10:25$$,
  $$11:10$$,
  null,
  $$https://www.happity.co.uk/islington/baby-toddler-classes#mini-mozart-baby-class-st-marys-wed-1025$$,
  null,
  null,
  0,
  $$0 months - 15 months$$,
  $$Islington$$,
  array[$$Wednesday$$],
  $$FREQ=WEEKLY;BYDAY=WE$$,
  $$Wednesday listing on Happity; term time only.$$
  ,
  $$Classical music-inspired baby class for babies and their grown-ups.$$
  ,
  $$Check Happity$$,
  true,
  $$Happity$$,
  $$https://www.happity.co.uk/islington/baby-toddler-classes#mini-mozart-baby-class-st-marys-wed-1025$$,
  null,
  $$https://www.happity.co.uk/islington/baby-toddler-classes#mini-mozart-baby-class-st-marys-wed-1025$$,
  null,
  '{}',
  null,
  null,
  array[$$Wednesday$$],
  $$weekly$$,
  $$Imported from Happity Islington listings. Verify live schedule and booking before travelling.$$
  ,
  $$published$$
),
(
  $$Music Tree - First Steps in Music 0-18$$,
  $$Music Tree, London N1$$,
  $$N1$$,
  null,
  null,
  $$family activity$$,
  $$11:00$$,
  $$11:45$$,
  null,
  $$https://www.happity.co.uk/islington/baby-toddler-classes#music-tree-first-steps-0-18-wed-1100$$,
  null,
  null,
  0,
  $$0 months - 18 months$$,
  $$Islington$$,
  array[$$Wednesday$$],
  $$FREQ=WEEKLY;BYDAY=WE$$,
  $$Wednesday listing on Happity; selected dates.$$
  ,
  $$Early music session for babies, with rhythm, songs and musical play.$$
  ,
  $$£25.00 - £39.60$$,
  true,
  $$Happity$$,
  $$https://www.happity.co.uk/islington/baby-toddler-classes#music-tree-first-steps-0-18-wed-1100$$,
  null,
  $$https://www.happity.co.uk/islington/baby-toddler-classes#music-tree-first-steps-0-18-wed-1100$$,
  null,
  '{}',
  null,
  null,
  array[$$Wednesday$$],
  $$weekly$$,
  $$Imported from Happity Islington listings. Verify live schedule and booking before travelling.$$
  ,
  $$published$$
),
(
  $$Monkey Music - Rock 'n' Roll$$,
  $$St Mary's Church, London N1$$,
  $$N1$$,
  null,
  null,
  $$family activity$$,
  $$11:30$$,
  $$12:00$$,
  null,
  $$https://www.happity.co.uk/islington/baby-toddler-classes#monkey-music-rock-n-roll-st-marys-wed-1130$$,
  null,
  null,
  0,
  $$3 months - 12 months$$,
  $$Islington$$,
  array[$$Wednesday$$],
  $$FREQ=WEEKLY;BYDAY=WE$$,
  $$Wednesday listing on Happity; term time only.$$
  ,
  $$Baby music class for very young babies, with songs and rhythm games.$$
  ,
  $$£12.75$$,
  true,
  $$Happity$$,
  $$https://www.happity.co.uk/islington/baby-toddler-classes#monkey-music-rock-n-roll-st-marys-wed-1130$$,
  null,
  $$https://www.happity.co.uk/islington/baby-toddler-classes#monkey-music-rock-n-roll-st-marys-wed-1130$$,
  null,
  '{}',
  null,
  null,
  array[$$Wednesday$$],
  $$weekly$$,
  $$Imported from Happity Islington listings. Verify live schedule and booking before travelling.$$
  ,
  $$published$$
),
(
  $$Little Movers Gym - Open Gym$$,
  $$Gracepoint, London N1$$,
  $$N1$$,
  null,
  null,
  $$soft play$$,
  $$09:30$$,
  $$10:30$$,
  null,
  $$https://www.happity.co.uk/islington/baby-toddler-classes#little-movers-gym-open-gym-gracepoint-wed-0930$$,
  null,
  null,
  0,
  $$6 months - 12 years$$,
  $$Islington$$,
  array[$$Wednesday$$],
  $$FREQ=WEEKLY;BYDAY=WE$$,
  $$Wednesday listing on Happity; term time only.$$
  ,
  $$Open gym session for active indoor play with babies, toddlers and children.$$
  ,
  $$£10.00$$,
  true,
  $$Happity$$,
  $$https://www.happity.co.uk/islington/baby-toddler-classes#little-movers-gym-open-gym-gracepoint-wed-0930$$,
  null,
  $$https://www.happity.co.uk/islington/baby-toddler-classes#little-movers-gym-open-gym-gracepoint-wed-0930$$,
  null,
  '{}',
  null,
  null,
  array[$$Wednesday$$],
  $$weekly$$,
  $$Imported from Happity Islington listings. Verify live schedule and booking before travelling.$$
  ,
  $$published$$
),
(
  $$TTA - Leaves & Colours: Nature Painting Workshop$$,
  $$N7 9DP, London N7$$,
  $$N7$$,
  null,
  null,
  $$family activity$$,
  $$10:00$$,
  $$11:00$$,
  null,
  $$https://www.happity.co.uk/islington/baby-toddler-classes#tta-leaves-colours-nature-painting-wed-1000$$,
  null,
  null,
  0,
  $$3 years - 5 years$$,
  $$Islington$$,
  array[$$Wednesday$$],
  $$FREQ=WEEKLY;BYDAY=WE$$,
  $$Wednesday listing on Happity; selected dates.$$
  ,
  $$Nature-themed painting workshop for preschoolers.$$
  ,
  $$£25.00$$,
  true,
  $$Happity$$,
  $$https://www.happity.co.uk/islington/baby-toddler-classes#tta-leaves-colours-nature-painting-wed-1000$$,
  null,
  $$https://www.happity.co.uk/islington/baby-toddler-classes#tta-leaves-colours-nature-painting-wed-1000$$,
  null,
  '{}',
  null,
  null,
  array[$$Wednesday$$],
  $$weekly$$,
  $$Imported from Happity Islington listings. Verify live schedule and booking before travelling.$$
  ,
  $$published$$
),
(
  $$Music Tree - First Steps in Music 18-36$$,
  $$Music Tree, London N1$$,
  $$N1$$,
  null,
  null,
  $$family activity$$,
  $$10:15$$,
  $$11:00$$,
  null,
  $$https://www.happity.co.uk/islington/baby-toddler-classes#music-tree-first-steps-18-36-wed-1015$$,
  null,
  null,
  0,
  $$18 months - 3 years$$,
  $$Islington$$,
  array[$$Wednesday$$],
  $$FREQ=WEEKLY;BYDAY=WE$$,
  $$Wednesday listing on Happity; selected dates.$$
  ,
  $$Music class for toddlers with songs, rhythm, movement and parent participation.$$
  ,
  $$£25.00 - £39.60$$,
  true,
  $$Happity$$,
  $$https://www.happity.co.uk/islington/baby-toddler-classes#music-tree-first-steps-18-36-wed-1015$$,
  null,
  $$https://www.happity.co.uk/islington/baby-toddler-classes#music-tree-first-steps-18-36-wed-1015$$,
  null,
  '{}',
  null,
  null,
  array[$$Wednesday$$],
  $$weekly$$,
  $$Imported from Happity Islington listings. Verify live schedule and booking before travelling.$$
  ,
  $$published$$
),
(
  $$Sense Stories by Kids at Play - 0-6 Months Sensory Class$$,
  $$The Ramsay Scout Centre, London N7$$,
  $$N7$$,
  null,
  null,
  $$sensory play$$,
  $$10:30$$,
  $$11:15$$,
  null,
  $$https://www.happity.co.uk/islington/baby-toddler-classes#sense-stories-0-6-ramsay-scout-centre-wed-1030$$,
  null,
  null,
  0,
  $$0 months - 6 months$$,
  $$Islington$$,
  array[$$Wednesday$$],
  $$FREQ=WEEKLY;BYDAY=WE$$,
  $$Wednesday listing on Happity; selected dates.$$
  ,
  $$Sensory storytelling class designed for very young babies.$$
  ,
  $$£11.00 - £44.00$$,
  true,
  $$Happity$$,
  $$https://www.happity.co.uk/islington/baby-toddler-classes#sense-stories-0-6-ramsay-scout-centre-wed-1030$$,
  null,
  $$https://www.happity.co.uk/islington/baby-toddler-classes#sense-stories-0-6-ramsay-scout-centre-wed-1030$$,
  null,
  '{}',
  null,
  null,
  array[$$Wednesday$$],
  $$weekly$$,
  $$Imported from Happity Islington listings. Verify live schedule and booking before travelling.$$
  ,
  $$published$$
),
(
  $$Sense Stories by Kids at Play$$,
  $$The Ramsay Scout Centre, London N7$$,
  $$N7$$,
  null,
  null,
  $$sensory play$$,
  $$11:45$$,
  $$12:30$$,
  null,
  $$https://www.happity.co.uk/islington/baby-toddler-classes#sense-stories-ramsay-scout-centre-wed-1145$$,
  null,
  null,
  0,
  $$0 months - 5 years$$,
  $$Islington$$,
  array[$$Wednesday$$],
  $$FREQ=WEEKLY;BYDAY=WE$$,
  $$Wednesday listing on Happity; selected dates.$$
  ,
  $$Sensory storytelling session for babies, toddlers and preschoolers.$$
  ,
  $$£11.00 - £44.00$$,
  true,
  $$Happity$$,
  $$https://www.happity.co.uk/islington/baby-toddler-classes#sense-stories-ramsay-scout-centre-wed-1145$$,
  null,
  $$https://www.happity.co.uk/islington/baby-toddler-classes#sense-stories-ramsay-scout-centre-wed-1145$$,
  null,
  '{}',
  null,
  null,
  array[$$Wednesday$$],
  $$weekly$$,
  $$Imported from Happity Islington listings. Verify live schedule and booking before travelling.$$
  ,
  $$published$$
)
on conflict (source_url) do update
set
  activity_name = excluded.activity_name,
  address = excluded.address,
  postcode = excluded.postcode,
  lat = excluded.lat,
  long = excluded.long,
  category = excluded.category,
  start_time = excluded.start_time,
  end_time = excluded.end_time,
  google_link = excluded.google_link,
  website = excluded.website,
  child_friendly_score = excluded.child_friendly_score,
  app_rating = excluded.app_rating,
  number_of_reviews = excluded.number_of_reviews,
  age_suitability = excluded.age_suitability,
  borough = excluded.borough,
  days_of_week = excluded.days_of_week,
  recurrence_rule = excluded.recurrence_rule,
  schedule_notes = excluded.schedule_notes,
  description = excluded.description,
  cost = excluded.cost,
  booking_required = excluded.booking_required,
  source_name = excluded.source_name,
  image_url = excluded.image_url,
  image_source_url = excluded.image_source_url,
  activity_date = excluded.activity_date,
  available_dates = excluded.available_dates,
  availability_start_date = excluded.availability_start_date,
  availability_end_date = excluded.availability_end_date,
  available_days_of_week = excluded.available_days_of_week,
  availability_type = excluded.availability_type,
  availability_notes = excluded.availability_notes,
  public_listing_status = excluded.public_listing_status;
