insert into public.activities (
  activity_name,
  address,
  postcode,
  lat,
  long,
  category,
  start_time,
  end_time,
  google_link,
  website,
  child_friendly_score,
  app_rating,
  number_of_reviews,
  age_suitability,
  borough,
  days_of_week,
  recurrence_rule,
  schedule_notes,
  description,
  cost,
  booking_required,
  source_name,
  source_url,
  activity_date,
  available_dates,
  availability_start_date,
  availability_end_date,
  available_days_of_week,
  availability_type,
  availability_notes
)
values
(
  'It Takes a Village Play Cafe',
  'Unit 2, 152 Billet Road, Walthamstow, London E17 5DR',
  'E17 5DR',
  51.600300,
  -0.040900,
  'Child-friendly cafes',
  '08:00',
  '17:00',
  'https://www.google.com/maps/search/?api=1&query=It%20Takes%20a%20Village%20Play%20Cafe%20152%20Billet%20Road%20E17%205DR',
  'https://www.ittakesavillageplaycafe.com/',
  null,
  null,
  0,
  'Babies, toddlers and young children',
  'Waltham Forest',
  array['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
  'FREQ=WEEKLY;BYDAY=MO,TU,WE,TH,FR,SA,SU',
  'Play cafe with bookable play sessions; check live booking page before travelling.',
  'Play cafe with a bespoke play frame, ball pit, role play area, coffee and snacks for parents and carers.',
  'Paid play session; cafe purchases separate',
  true,
  'It Takes a Village Play Cafe',
  'https://www.ittakesavillageplaycafe.com/',
  null,
  '{}',
  null,
  null,
  array['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
  'daily',
  'Open most days for play, coffee and snacks; book ahead for play sessions.'
),
(
  'Le Delice in the Park at Lloyd Park',
  'Aveling Centre, Lloyd Park, Forest Road, Walthamstow, London E17 4PP',
  'E17 4PP',
  51.592900,
  -0.020700,
  'Child-friendly cafes',
  '09:00',
  '17:00',
  'https://www.google.com/maps/search/?api=1&query=Le%20Delice%20in%20the%20Park%20Lloyd%20Park%20E17%204PP',
  'https://www.ledelicee17.co.uk/about-us',
  null,
  null,
  0,
  'All ages',
  'Waltham Forest',
  array['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
  'FREQ=WEEKLY;BYDAY=MO,TU,WE,TH,FR,SA,SU',
  'Venue states 9am to 5pm in autumn/winter and 9am to 6pm in spring/summer.',
  'Family-focused park cafe next to Lloyd Park play spaces, William Morris Gallery and baby-change facilities in the park cafe/toilets.',
  'Menu prices vary',
  false,
  'Le Delice E17',
  'https://www.ledelicee17.co.uk/about-us#lloyd-park',
  null,
  '{}',
  null,
  null,
  array['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
  'daily',
  'Daily cafe hours vary by season; check the venue page before travelling.'
),
(
  'The Homemade Community Cafe at Higham Hill Park',
  'Hecham Close, Higham Hill Park, London E17 5QT',
  'E17 5QT',
  51.598200,
  -0.038400,
  'Child-friendly cafes',
  '09:30',
  '15:30',
  'https://www.google.com/maps/search/?api=1&query=The%20Homemade%20Community%20Cafe%20Hecham%20Close%20E17%205QT',
  'https://www.walthamforest.gov.uk/families-young-people-and-children/parenting-and-family-support/best-start-family-hubs-directory/homemade-community-cafe',
  null,
  null,
  0,
  'Families with children aged 0 to 5',
  'Waltham Forest',
  '{}',
  null,
  'Community cafe hosting Family Hub events; check Family Hub listings for timed sessions.',
  'Community cafe in Higham Hill Park linked to Waltham Forest Family Hubs, with refreshments and parent/family support activity links.',
  'Free entry; purchases vary',
  false,
  'London Borough of Waltham Forest Family Hubs',
  'https://www.walthamforest.gov.uk/families-young-people-and-children/parenting-and-family-support/best-start-family-hubs-directory/homemade-community-cafe',
  null,
  '{}',
  null,
  null,
  '{}',
  'unknown',
  'Use as a venue listing; check the Family Hub events page for current dates and times.'
),
(
  'Lloyd Park playgrounds and sandpit',
  'Lloyd Park, Forest Road, Walthamstow, London E17 4PP',
  'E17 4PP',
  51.592800,
  -0.020500,
  'Parks & outdoor play',
  '08:00',
  '20:00',
  'https://www.google.com/maps/search/?api=1&query=Lloyd%20Park%20Forest%20Road%20Walthamstow%20E17%204PP',
  'https://www.walthamforest.gov.uk/libraries-arts-parks-and-leisure/parks-and-open-spaces/lloyd-park',
  null,
  null,
  0,
  'All ages',
  'Waltham Forest',
  array['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
  'FREQ=WEEKLY;BYDAY=MO,TU,WE,TH,FR,SA,SU',
  'Park is available daily; cafe and toilets follow cafe hours.',
  'Victorian park with natural play, play area, sandpit, scooter/skate areas, cafe, baby change and William Morris Gallery nearby.',
  'Free',
  false,
  'London Borough of Waltham Forest parks',
  'https://www.walthamforest.gov.uk/libraries-arts-parks-and-leisure/parks-and-open-spaces/lloyd-park',
  null,
  '{}',
  null,
  null,
  array['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
  'daily',
  'Outdoor park listing; check council page for park opening-hour changes.'
),
(
  'Walthamstow Wetlands family nature visit',
  'Walthamstow Wetlands, 2 Forest Road, London N17 9NH',
  'N17 9NH',
  51.586000,
  -0.049500,
  'Parks & outdoor play',
  '09:30',
  '17:00',
  'https://www.google.com/maps/search/?api=1&query=Walthamstow%20Wetlands%202%20Forest%20Road%20N17%209NH',
  'https://www.wildlondon.org.uk/nature-reserves/walthamstow-wetlands',
  null,
  null,
  0,
  'All ages',
  'Waltham Forest',
  array['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
  'FREQ=WEEKLY;BYDAY=MO,TU,WE,TH,FR,SA,SU',
  'April to September hours are 9:30am to 5pm; October to March closes earlier.',
  'Large urban wetland nature reserve with walks, wildlife, cafe, toilets and family-friendly nature trails.',
  'Free entry',
  false,
  'London Wildlife Trust',
  'https://www.wildlondon.org.uk/nature-reserves/walthamstow-wetlands',
  null,
  '{}',
  '2026-04-01',
  '2026-09-30',
  array['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
  'seasonal',
  'Listed with April-September hours; winter hours are shorter.'
),
(
  'William Morris Gallery family visit',
  'William Morris Gallery, Lloyd Park, Forest Road, Walthamstow, London E17 4PP',
  'E17 4PP',
  51.591700,
  -0.020700,
  'Museums & culture',
  '10:00',
  '17:00',
  'https://www.google.com/maps/search/?api=1&query=William%20Morris%20Gallery%20Lloyd%20Park%20E17%204PP',
  'https://www.wmgallery.org.uk/learn/families/',
  null,
  null,
  0,
  'Families; under-5 sessions and family trails available',
  'Waltham Forest',
  array['Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
  'FREQ=WEEKLY;BYDAY=TU,WE,TH,FR,SA,SU',
  'Gallery is normally open Tuesday to Sunday, 10am to 5pm; check renewal-project closures.',
  'Free gallery with family trails, hands-on exhibits, Mini Morris under-5 sessions and baby changing facilities.',
  'Free; donations welcome',
  false,
  'William Morris Gallery',
  'https://www.wmgallery.org.uk/learn/families/',
  null,
  '{}',
  null,
  null,
  array['Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
  'weekly',
  'Check the gallery site for temporary 2026 renewal closures.'
),
(
  'William Morris Gallery Family Day in the Park: Morris''s Magical Menagerie',
  'William Morris Gallery, Lloyd Park, Forest Road, Walthamstow, London E17 4PP',
  'E17 4PP',
  51.591700,
  -0.020700,
  'Family activities',
  '13:00',
  '16:00',
  'https://www.google.com/maps/search/?api=1&query=William%20Morris%20Gallery%20Lloyd%20Park%20E17%204PP',
  'https://www.walthamforest.gov.uk/events/william-morris-gallery-family-day-park-morriss-magical-menagerie',
  null,
  null,
  0,
  'Families with children; most suitable for ages 4+',
  'Waltham Forest',
  array['Saturday'],
  'FREQ=DAILY;COUNT=1',
  'Saturday 8 August 2026, 1pm to 4pm.',
  'Drop-in family day making colourful animal masks inspired by Lloyd Park wildlife, followed by a summer family trail.',
  'Free',
  false,
  'London Borough of Waltham Forest events',
  'https://www.walthamforest.gov.uk/events/william-morris-gallery-family-day-park-morriss-magical-menagerie',
  '2026-08-08',
  array['2026-08-08'::date],
  '2026-08-08',
  '2026-08-08',
  array['Saturday'],
  'one_off',
  'One-off event on Saturday 8 August 2026.'
),
(
  'The Highams Park playground and Humphry''s Cafe',
  'The Highams Park, Tamworth Avenue, London E4 9LA',
  'E4 9LA',
  51.608900,
  -0.000900,
  'Parks & outdoor play',
  '08:00',
  '18:00',
  'https://www.google.com/maps/search/?api=1&query=The%20Highams%20Park%20Tamworth%20Avenue%20E4%209LA',
  'https://highamspark.london/highams-park/the-highams-park/',
  null,
  null,
  0,
  'Under 7s and older children',
  'Waltham Forest',
  array['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
  'FREQ=WEEKLY;BYDAY=MO,TU,WE,TH,FR,SA,SU',
  'Community listing notes a playground for under-7s, older equipment including zip wire, and Humphry''s Cafe.',
  'Neighbourhood park with playground, older-child equipment, cafe and toilets available to park users.',
  'Free',
  false,
  'Highams Park Portal',
  'https://highamspark.london/highams-park/the-highams-park/',
  null,
  '{}',
  null,
  null,
  array['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
  'daily',
  'Outdoor park listing; check local notices for cafe hours.'
),
(
  'Dreami Play Cafe',
  'Unit 3, Oakwood House, 422 Hackney Road, Hackney, London E2 7SY',
  'E2 7SY',
  51.532200,
  -0.061900,
  'Child-friendly cafes',
  '09:30',
  '17:00',
  'https://www.google.com/maps/search/?api=1&query=Dreami%20Play%20Cafe%20422%20Hackney%20Road%20E2%207SY',
  'https://www.dreami.uk/',
  null,
  null,
  0,
  'Children aged 0 to 6',
  'Hackney',
  array['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
  'FREQ=WEEKLY;BYDAY=MO,TU,WE,TH,FR',
  'Open Monday to Friday 9:30am to 5pm; weekends usually private hire or occasional play sessions.',
  'Bilingual play cafe for babies, toddlers and young children with Montessori-inspired toys, creative play and parent seating.',
  'Paid play session; cafe purchases vary',
  true,
  'Dreami Play Cafe',
  'https://www.dreami.uk/',
  null,
  '{}',
  null,
  null,
  array['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
  'weekly',
  'Weekends are usually private hire unless extra sessions are released.'
),
(
  'Frizzante Cafe at Hackney City Farm',
  'Hackney City Farm, 1a Goldsmiths Row, London E2 8QA',
  'E2 8QA',
  51.532800,
  -0.061200,
  'Child-friendly cafes',
  '10:00',
  '16:30',
  'https://www.google.com/maps/search/?api=1&query=Frizzante%20Cafe%20Hackney%20City%20Farm%201a%20Goldsmiths%20Row%20E2%208QA',
  'https://hackneycityfarm.co.uk/visit/',
  null,
  null,
  0,
  'All ages',
  'Hackney',
  array['Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
  'FREQ=WEEKLY;BYDAY=TU,WE,TH,FR,SA,SU',
  'Farmyard is open Tuesday to Sunday, 10am to 4:30pm; cafe opening times may vary.',
  'Farm cafe stop paired with animals, gardens, accessible toilet and baby changing facilities.',
  'Free farm entry; menu prices vary',
  false,
  'Hackney City Farm',
  'https://hackneycityfarm.co.uk/visit/#cafe',
  null,
  '{}',
  null,
  null,
  array['Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
  'weekly',
  'Cafe is a separate business; check cafe opening times before travelling.'
),
(
  'Hackney City Farm family visit',
  'Hackney City Farm, 1a Goldsmiths Row, London E2 8QA',
  'E2 8QA',
  51.532800,
  -0.061200,
  'Family activities',
  '10:00',
  '16:30',
  'https://www.google.com/maps/search/?api=1&query=Hackney%20City%20Farm%201a%20Goldsmiths%20Row%20E2%208QA',
  'https://hackneycityfarm.co.uk/visit/',
  null,
  null,
  0,
  'All ages; supervise children around animals',
  'Hackney',
  array['Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
  'FREQ=WEEKLY;BYDAY=TU,WE,TH,FR,SA,SU',
  'Farmyard and gardens are open Tuesday to Sunday, 10am to 4:30pm; closed Mondays except bank holidays.',
  'Free city farm visit with animals, gardens, handwashing points, baby changing and cafe on site.',
  'Free entry; donations welcome',
  false,
  'Hackney City Farm',
  'https://hackneycityfarm.co.uk/visit/#farmyard',
  null,
  '{}',
  null,
  null,
  array['Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
  'weekly',
  'Closed Mondays except bank holidays.'
),
(
  'Clissold Park playground, animal enclosures and splash pad',
  'Clissold Park, Green Lanes, London N4 2EY',
  'N4 2EY',
  51.561600,
  -0.090700,
  'Parks & outdoor play',
  '08:00',
  '20:00',
  'https://www.google.com/maps/search/?api=1&query=Clissold%20Park%20Green%20Lanes%20N4%202EY',
  'https://www.hackney.gov.uk/libraries-parks-and-leisure/parks-and-green-spaces/parks-list/clissold-park-and-house',
  null,
  null,
  0,
  'All ages',
  'Hackney',
  array['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
  'FREQ=WEEKLY;BYDAY=MO,TU,WE,TH,FR,SA,SU',
  'Park is available daily; splash pad is seasonal May to September.',
  'Large family park with children''s play area, animal enclosures, Fink''s Pump House cafe, toilets, splash pad, wheels park and ponds.',
  'Free',
  false,
  'Hackney Council parks',
  'https://www.hackney.gov.uk/libraries-parks-and-leisure/parks-and-green-spaces/parks-list/clissold-park-and-house',
  null,
  '{}',
  null,
  null,
  array['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
  'daily',
  'Splash pad has separate seasonal availability.'
),
(
  'Clissold Park splash pad',
  'Clissold Park, Green Lanes, London N4 2EY',
  'N4 2EY',
  51.561600,
  -0.090700,
  'Parks & outdoor play',
  '11:00',
  '18:00',
  'https://www.google.com/maps/search/?api=1&query=Clissold%20Park%20Splash%20Pad%20N4%202EY',
  'https://news.hackney.gov.uk/news/clissold-park-splash-pad-returns-this-month',
  null,
  null,
  0,
  'Children under 16',
  'Hackney',
  array['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
  'FREQ=WEEKLY;BYDAY=MO,TU,WE,TH,FR,SA,SU',
  'Seasonal outdoor water play; source notes weekends from May and daily during school summer holidays.',
  'Seasonal splash pad with water jets, sprays and booking/walk-up sessions.',
  'Free sessions available',
  true,
  'Hackney Council News',
  'https://news.hackney.gov.uk/news/clissold-park-splash-pad-returns-this-month',
  null,
  '{}',
  '2026-05-01',
  '2026-09-30',
  array['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
  'seasonal',
  'May to September season; check Better booking page for specific bookable slots.'
),
(
  'Hackney Museum family visit',
  'Hackney Museum, 1 Reading Lane, London E8 1GQ',
  'E8 1GQ',
  51.545000,
  -0.055500,
  'Museums & culture',
  '09:30',
  '17:30',
  'https://www.google.com/maps/search/?api=1&query=Hackney%20Museum%201%20Reading%20Lane%20E8%201GQ',
  'https://hackney-museum.hackney.gov.uk/visit/',
  null,
  null,
  0,
  'Families and children',
  'Hackney',
  array['Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
  'FREQ=WEEKLY;BYDAY=TU,WE,TH,FR,SA',
  'Open Tuesday to Saturday, with Thursday evening opening; closed Sunday, Monday and public holidays.',
  'Local museum sharing Hackney stories, with touchable objects, oral histories, interactive elements and family-friendly exhibitions.',
  'Free',
  false,
  'Hackney Museum',
  'https://hackney-museum.hackney.gov.uk/visit/',
  null,
  '{}',
  null,
  null,
  array['Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
  'weekly',
  'Thursday opening runs later than the default end time shown here.'
),
(
  'Museum of the Home family visit',
  'Museum of the Home, 136 Kingsland Road, London E2 8EA',
  'E2 8EA',
  51.531900,
  -0.076900,
  'Museums & culture',
  '10:00',
  '17:00',
  'https://www.google.com/maps/search/?api=1&query=Museum%20of%20the%20Home%20136%20Kingsland%20Road%20E2%208EA',
  'https://museumofthehome.org.uk/plan-your-visit/',
  null,
  null,
  0,
  'Children of all ages; children must be accompanied',
  'Hackney',
  array['Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
  'FREQ=WEEKLY;BYDAY=TU,WE,TH,FR,SA,SU',
  'Museum is open Tuesday to Sunday, 10am to 5pm; gardens have separate opening.',
  'Free museum with family visit resources, gardens, lunch room and facilities for babies and children.',
  'Free',
  false,
  'Museum of the Home',
  'https://museumofthehome.org.uk/plan-your-visit/',
  null,
  '{}',
  null,
  null,
  array['Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
  'weekly',
  'Closed Mondays except bank holidays; check holiday closures.'
),
(
  'Woodberry Down Children and Family Hub stay and play',
  'Woodberry Down Children and Family Hub, Spring Park Drive, off Green Lanes, London N4 2NP',
  'N4 2NP',
  51.571300,
  -0.096700,
  'Stay & play',
  '10:00',
  '12:00',
  'https://www.google.com/maps/search/?api=1&query=Woodberry%20Down%20Children%20and%20Family%20Hub%20N4%202NP',
  'https://www.woodberrydowncfhub.hackney.gov.uk/',
  null,
  null,
  0,
  'Families with children aged 0 to 5',
  'Hackney',
  array['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
  'FREQ=WEEKLY;BYDAY=MO,TU,WE,TH,FR,SA',
  'Hub is open Monday to Saturday and publishes current stay-and-play sessions on its What''s On section.',
  'Children and Family Hub with stay-and-play activities, music sessions, parenting support and social space.',
  'Free',
  false,
  'Woodberry Down Children and Family Hub',
  'https://www.woodberrydowncfhub.hackney.gov.uk/',
  null,
  '{}',
  null,
  null,
  array['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
  'weekly',
  'Use hub What''s On listings for exact session dates and times.'
),
(
  'London Fields play areas',
  'London Fields, Eleanor Road, London E8 3EU',
  'E8 3EU',
  51.541200,
  -0.061000,
  'Parks & outdoor play',
  '08:00',
  '20:00',
  'https://www.google.com/maps/search/?api=1&query=London%20Fields%20play%20areas%20E8%203EU',
  'https://www.hackney.gov.uk/libraries-parks-and-leisure/parks-and-green-spaces/playgrounds',
  null,
  null,
  0,
  'All ages',
  'Hackney',
  array['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
  'FREQ=WEEKLY;BYDAY=MO,TU,WE,TH,FR,SA,SU',
  'Hackney playground list notes two play areas at London Fields.',
  'Neighbourhood park play areas near Broadway Market and London Fields open space.',
  'Free',
  false,
  'Hackney Council playgrounds',
  'https://www.hackney.gov.uk/libraries-parks-and-leisure/parks-and-green-spaces/playgrounds#london-fields',
  null,
  '{}',
  null,
  null,
  array['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
  'daily',
  'Outdoor play-area listing; check council notices for refurbishments.'
),
(
  'Discover Children''s Story Centre: Story Worlds and Story Garden',
  'Discover Children''s Story Centre, 383-387 High Street Stratford, London E15 4QZ',
  'E15 4QZ',
  51.541600,
  0.002600,
  'Museums & culture',
  '10:00',
  '17:00',
  'https://www.google.com/maps/search/?api=1&query=Discover%20Children%27s%20Story%20Centre%20383-387%20High%20Street%20Stratford%20E15%204QZ',
  'https://discover.org.uk/your-visit/',
  null,
  null,
  0,
  'Children aged 0 to 11 and families',
  'Newham',
  array['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
  'FREQ=WEEKLY;BYDAY=MO,TU,WE,TH,FR,SA,SU',
  'Open every day, 10am to 5pm; advance booking recommended for Story Worlds and add-on events.',
  'Children''s story centre with immersive Story Worlds, Story Garden, cafe and bookshop.',
  'Paid entry; Newham/concession pricing available',
  true,
  'Discover Children''s Story Centre',
  'https://discover.org.uk/your-visit/',
  null,
  '{}',
  null,
  null,
  array['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
  'daily',
  'Open daily except occasional closure dates listed by the venue.'
),
(
  'Discover 0-5 Storytelling: Not-A-Box',
  'Discover Children''s Story Centre, 383-387 High Street Stratford, London E15 4QZ',
  'E15 4QZ',
  51.541600,
  0.002600,
  'Story & rhyme time',
  '10:00',
  '17:00',
  'https://www.google.com/maps/search/?api=1&query=Discover%20Children%27s%20Story%20Centre%20Stratford',
  'https://discover.org.uk/',
  null,
  null,
  0,
  '0 to 5 years',
  'Newham',
  array['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
  'FREQ=DAILY;UNTIL=20260727',
  'Runs 20 June to 27 July 2026, every day at various times.',
  'Short 0-5 storytelling session inspired by Not a Box, designed for young children and grown-ups.',
  'Add-on ticket',
  true,
  'Discover Children''s Story Centre events',
  'https://discover.org.uk/#not-a-box-0-5s-storytelling',
  null,
  '{}',
  '2026-06-20',
  '2026-07-27',
  array['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
  'date_range',
  'Available daily from 20 June to 27 July 2026 at various times.'
),
(
  'Discover Baby and Toddler Sensory Space',
  'Discover Children''s Story Centre, 383-387 High Street Stratford, London E15 4QZ',
  'E15 4QZ',
  51.541600,
  0.002600,
  'Baby sensory',
  '10:00',
  '17:00',
  'https://www.google.com/maps/search/?api=1&query=Discover%20Baby%20and%20Toddler%20Sensory%20Space%20E15%204QZ',
  'https://discover.org.uk/',
  null,
  null,
  0,
  '0 to 2 years',
  'Newham',
  array['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
  'FREQ=DAILY',
  'Daily from 20 June 2026; free with entry ticket according to the venue listing.',
  'Enchanted garden-themed sensory play room for babies, toddlers and their grown-ups.',
  'Free with Discover entry ticket',
  true,
  'Discover Children''s Story Centre events',
  'https://discover.org.uk/#baby-and-toddler-sensory-space',
  null,
  '{}',
  '2026-06-20',
  null,
  array['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
  'date_range',
  'Daily from 20 June 2026; check venue for session times.'
),
(
  'Timber Lodge Cafe at Tumbling Bay',
  'Timber Lodge Cafe, Queen Elizabeth Olympic Park, Stratford, London E20 2AD',
  'E20 2AD',
  51.548400,
  -0.015300,
  'Child-friendly cafes',
  '09:00',
  '17:00',
  'https://www.google.com/maps/search/?api=1&query=Timber%20Lodge%20Cafe%20Queen%20Elizabeth%20Olympic%20Park%20E20%202AD',
  'https://www.queenelizabetholympicpark.co.uk/eat-drink/timber-lodge-cafe-your-parkside-dining-destination',
  null,
  null,
  0,
  'All ages',
  'Newham',
  array['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
  'FREQ=WEEKLY;BYDAY=MO,TU,WE,TH,FR,SA,SU',
  'Park cafe next to Tumbling Bay; check cafe site for live hours.',
  'Parkside cafe described by the park as perfect for kids because it sits next to Tumbling Bay adventure playground.',
  'Menu prices vary',
  false,
  'Queen Elizabeth Olympic Park',
  'https://www.queenelizabetholympicpark.co.uk/eat-drink/timber-lodge-cafe-your-parkside-dining-destination',
  null,
  '{}',
  null,
  null,
  array['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
  'daily',
  'Check live cafe hours before travelling.'
),
(
  'Tumbling Bay Playground',
  'Tumbling Bay Playground, Queen Elizabeth Olympic Park, Stratford, London E20 2AD',
  'E20 2AD',
  51.548400,
  -0.015300,
  'Parks & outdoor play',
  '10:00',
  '17:00',
  'https://www.google.com/maps/search/?api=1&query=Tumbling%20Bay%20Playground%20Queen%20Elizabeth%20Olympic%20Park',
  'https://www.queenelizabetholympicpark.co.uk/explore-park/parklands-and-playgrounds/tumbling-bay-playground',
  null,
  null,
  0,
  'All ages',
  'Newham',
  array['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
  'FREQ=WEEKLY;BYDAY=MO,TU,WE,TH,FR,SA,SU',
  'Playground availability can change during maintenance; check Queen Elizabeth Olympic Park updates.',
  'Nature-inspired playground with treehouses, rock pools, sand pits, rope bridges, zip wires and seating for parents.',
  'Free',
  false,
  'Queen Elizabeth Olympic Park',
  'https://www.queenelizabetholympicpark.co.uk/explore-park/parklands-and-playgrounds/tumbling-bay-playground',
  null,
  '{}',
  null,
  null,
  array['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
  'daily',
  'Check park updates for temporary maintenance closures.'
),
(
  'Queen Elizabeth Olympic Park fountains and play areas',
  'Queen Elizabeth Olympic Park, Stratford, London E20 2ST',
  'E20 2ST',
  51.543300,
  -0.016600,
  'Parks & outdoor play',
  '10:00',
  '17:00',
  'https://www.google.com/maps/search/?api=1&query=Queen%20Elizabeth%20Olympic%20Park%20Playgrounds%20Stratford',
  'https://www.queenelizabetholympicpark.co.uk/explore-park/parklands-and-playgrounds/playgrounds',
  null,
  null,
  0,
  'All ages',
  'Newham',
  array['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
  'FREQ=WEEKLY;BYDAY=MO,TU,WE,TH,FR,SA,SU',
  'Water fountains are listed as on until October, around 10am to 5pm except London Stadium event days.',
  'Large park with multiple play areas, climbing wall and seasonal fountains suitable for family days out.',
  'Free',
  false,
  'Queen Elizabeth Olympic Park',
  'https://www.queenelizabetholympicpark.co.uk/explore-park/parklands-and-playgrounds/playgrounds',
  null,
  '{}',
  '2026-04-01',
  '2026-10-31',
  array['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
  'seasonal',
  'Fountains run seasonally and are affected by London Stadium event days.'
),
(
  'West Ham Park playground and paddling pool',
  'West Ham Park, Upton Lane, London E7 9PU',
  'E7 9PU',
  51.539900,
  0.033100,
  'Parks & outdoor play',
  '08:00',
  '20:00',
  'https://www.google.com/maps/search/?api=1&query=West%20Ham%20Park%20Upton%20Lane%20E7%209PU',
  'https://www.cityoflondon.gov.uk/things-to-do/green-spaces/west-ham-park/visit-west-ham-park',
  null,
  null,
  0,
  'All ages',
  'Newham',
  array['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
  'FREQ=WEEKLY;BYDAY=MO,TU,WE,TH,FR,SA,SU',
  'Park facilities include children''s playground and paddling pool; check seasonal status before travelling.',
  'Large Newham green space with ornamental gardens, children''s playground, paddling pool and sports facilities.',
  'Free',
  false,
  'City of London West Ham Park',
  'https://www.cityoflondon.gov.uk/things-to-do/green-spaces/west-ham-park/visit-west-ham-park',
  null,
  '{}',
  null,
  null,
  array['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
  'daily',
  'Paddling-pool availability may be seasonal.'
),
(
  'East Ham Library Family Hub',
  'East Ham Library, 328 Barking Road, London E6 2RT',
  'E6 2RT',
  51.532900,
  0.055600,
  'Family hubs',
  '10:00',
  '16:00',
  'https://www.google.com/maps/search/?api=1&query=East%20Ham%20Library%20328%20Barking%20Road%20E6%202RT',
  'https://families.newham.gov.uk/kb5/newham/directory/familyhub.page?familyhubchannel=5-1',
  null,
  null,
  0,
  'Families in East Ham, Plaistow and surrounding areas',
  'Newham',
  array['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
  'FREQ=WEEKLY;BYDAY=MO,TU,WE,TH,FR',
  'Family Hub provides baby and toddler groups, family support and early years activities; check hub timetable.',
  'Welcoming Family Hub at East Ham Library with baby and toddler groups, wellbeing services and parenting support.',
  'Free',
  false,
  'Newham Families',
  'https://families.newham.gov.uk/kb5/newham/directory/familyhub.page?familyhubchannel=5-1',
  null,
  '{}',
  null,
  null,
  array['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
  'weekly',
  'Use Newham Family Hub listings for current session dates and times.'
),
(
  'Carpenters Cafe children''s toys',
  'Carpenters TMO Community Hall, 17 Doran Walk, Stratford, London E15 2JL',
  'E15 2JL',
  51.540900,
  -0.008500,
  'Child-friendly cafes',
  '10:00',
  '15:00',
  'https://www.google.com/maps/search/?api=1&query=Carpenters%20Cafe%2017%20Doran%20Walk%20E15%202JL',
  'https://families.newham.gov.uk/kb5/newham/directory/service.page?familychannel=1-1&id=9Hk1rjt-v9E',
  null,
  null,
  0,
  'Families and children',
  'Newham',
  '{}',
  null,
  'Newham Families lists Carpenters Cafe children''s toys service; confirm current opening before visiting.',
  'Community cafe/service listing for children''s toys at Carpenters TMO Community Hall.',
  'Check with venue',
  false,
  'Newham Families',
  'https://families.newham.gov.uk/kb5/newham/directory/service.page?familychannel=1-1&id=9Hk1rjt-v9E',
  null,
  '{}',
  null,
  null,
  '{}',
  'unknown',
  'Current opening days are not listed on the source page; phone or email before travelling.'
),
(
  'Royal Docks Kids Summer Splash',
  'Royal Victoria Dock, London E16 1AG',
  'E16 1AG',
  51.507900,
  0.017600,
  'Family activities',
  '10:00',
  '18:00',
  'https://www.google.com/maps/search/?api=1&query=Royal%20Victoria%20Dock%20Kids%20Summer%20Splash%20E16%201AG',
  'https://www.royaldocks.london/whats-on/summer-family-fun-at-kids-summer-splash',
  null,
  null,
  0,
  'Families; children under 8 using the lido must be accompanied',
  'Newham',
  array['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
  'FREQ=DAILY;UNTIL=20260821',
  '1 to 21 August 2026, daily 10am to 6pm; no booking required according to source.',
  'Free summer family event with lido, shallow end, sandpits, deckchairs, craft workshops, storytelling and family performances.',
  'Free',
  false,
  'Royal Docks',
  'https://www.royaldocks.london/whats-on/summer-family-fun-at-kids-summer-splash',
  null,
  '{}',
  '2026-08-01',
  '2026-08-21',
  array['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
  'date_range',
  'Daily from 1 to 21 August 2026, 10am to 6pm.'
)
on conflict (source_url) do update set
  activity_name = excluded.activity_name,
  address = excluded.address,
  postcode = excluded.postcode,
  lat = excluded.lat,
  long = excluded.long,
  category = excluded.category,
  start_time = excluded.start_time,
  end_time = excluded.end_time,
  google_link = excluded.google_link,
  website = excluded.website,
  child_friendly_score = excluded.child_friendly_score,
  app_rating = excluded.app_rating,
  number_of_reviews = excluded.number_of_reviews,
  age_suitability = excluded.age_suitability,
  borough = excluded.borough,
  days_of_week = excluded.days_of_week,
  recurrence_rule = excluded.recurrence_rule,
  schedule_notes = excluded.schedule_notes,
  description = excluded.description,
  cost = excluded.cost,
  booking_required = excluded.booking_required,
  source_name = excluded.source_name,
  activity_date = excluded.activity_date,
  available_dates = excluded.available_dates,
  availability_start_date = excluded.availability_start_date,
  availability_end_date = excluded.availability_end_date,
  available_days_of_week = excluded.available_days_of_week,
  availability_type = excluded.availability_type,
  availability_notes = excluded.availability_notes;
