export const sampleActivities = [
  {
    activity_id: 'sample-1',
    activity_name: 'Stay and play at Barclay Primary School, Leyton',
    address: 'Barclay Primary School, 155 Canterbury Road, London E10 6EJ',
    postcode: 'E10 6EJ',
    lat: 51.575756,
    long: -0.000933,
    category: 'baby stay and play',
    start_time: '09:15',
    end_time: '10:15',
    time_window: 'morning',
    borough: 'Waltham Forest',
    days_of_week: ['Thursday'],
    website: 'https://www.walthamforest.gov.uk/events/stay-and-play-barclay-primary-school-leyton',
    google_link:
      'https://www.google.com/maps/search/?api=1&query=Barclay%20Primary%20School%20155%20Canterbury%20Road%20London%20E10%206EJ',
    child_friendly_score: 4.4,
    app_rating: 4.6,
    number_of_reviews: 12,
    age_suitability: 'Birth to 4 years',
    description: 'Creative stay-and-play session with toys, social time, and space for parents and carers to meet.',
    cost: 'GBP 1 per child',
    followerNames: ['Maya'],
  },
  {
    activity_id: 'sample-2',
    activity_name: 'Play and learn for under-2s at Walthamstow Family Hub',
    address: 'Walthamstow Family Hub, 313 Billet Road, London E17 5PX',
    postcode: 'E17 5PX',
    lat: 51.597912,
    long: -0.040839,
    category: 'baby stay and play',
    start_time: '09:30',
    end_time: '11:00',
    time_window: 'morning',
    borough: 'Waltham Forest',
    days_of_week: ['Thursday'],
    website: 'https://www.walthamforest.gov.uk/events/play-and-learn-under-2s-best-start-family-hub-walthamstow',
    google_link:
      'https://www.google.com/maps/search/?api=1&query=Walthamstow%20Family%20Hub%20313%20Billet%20Road%20E17%205PX',
    child_friendly_score: 4.8,
    app_rating: 4.7,
    number_of_reviews: 18,
    age_suitability: 'Under 2s',
    description: 'Interactive early-years play focused on home learning, routines, language, movement, and connection.',
    cost: 'Free',
    followerNames: ['Noor', 'Izzie'],
  },
  {
    activity_id: 'sample-3',
    activity_name: 'Grow Wild Explorer at Lloyd Park',
    address: 'The Lloyd Park Centre, Winns Avenue Entrance, London E17 5JW',
    postcode: 'E17 5JW',
    lat: 51.593406,
    long: -0.022032,
    category: 'outdoor play',
    start_time: '09:30',
    end_time: '10:30',
    time_window: 'morning',
    borough: 'Waltham Forest',
    days_of_week: ['Thursday'],
    website: 'https://www.walthamforest.gov.uk/events/grow-wild-explorer-first-session',
    google_link:
      'https://www.google.com/maps/search/?api=1&query=The%20Lloyd%20Park%20Centre%20Winns%20Avenue%20Entrance%20E17%205JW',
    child_friendly_score: 4.9,
    app_rating: 4.8,
    number_of_reviews: 21,
    age_suitability: 'Under 5s',
    description: 'Outdoor adventure playground with climbing, sliding, hopping, jumping, and exploring.',
    cost: 'Free',
    followerNames: [],
  },
  {
    activity_id: 'sample-4',
    activity_name: 'Flourish post-natal support group at Chingford Family Hub',
    address: 'Chingford Family Hub, Wyemead Centre, 5 Oaks Grove, Chingford E4 6EY',
    postcode: 'E4 6EY',
    lat: 51.625359,
    long: 0.009538,
    category: 'post-natal support',
    start_time: '10:00',
    end_time: '12:00',
    time_window: 'morning',
    borough: 'Waltham Forest',
    days_of_week: ['Monday'],
    website: 'https://www.walthamforest.gov.uk/events/flourish-post-natal-support-group-best-start-family-hub-chingford',
    google_link:
      'https://www.google.com/maps/search/?api=1&query=Chingford%20Family%20Hub%20Wyemead%20Centre%205%20Oaks%20Grove%20E4%206EY',
    child_friendly_score: 4.7,
    app_rating: 4.5,
    number_of_reviews: 9,
    age_suitability: 'Mothers with babies',
    description: 'Support group for mothers navigating the transition into motherhood.',
    cost: 'Free',
    followerNames: ['Maya'],
  },
  {
    activity_id: 'sample-5',
    activity_name: 'Sensory Play and Learn at Leytonstone Family Hub',
    address: 'Leytonstone Family Hub, The Junction, 2-8 Cathall Road, London E11 4LF',
    postcode: 'E11 4LF',
    lat: 51.55813,
    long: 0.006474,
    category: 'sensory play',
    start_time: '10:00',
    end_time: '11:30',
    time_window: 'morning',
    borough: 'Waltham Forest',
    days_of_week: ['Monday'],
    website: 'https://www.walthamforest.gov.uk/events/sensory-play-and-learn-best-start-family-hub-leytonstone',
    google_link:
      'https://www.google.com/maps/search/?api=1&query=Leytonstone%20Family%20Hub%20The%20Junction%202-8%20Cathall%20Road%20E11%204LF',
    child_friendly_score: 4.8,
    app_rating: 4.7,
    number_of_reviews: 15,
    age_suitability: 'Under 5s, including children with SEND or developmental delay',
    description: 'Inclusive sensory play session for under-fives.',
    cost: 'Free',
    followerNames: ['Leah'],
  },
  {
    activity_id: 'sample-6',
    activity_name: 'HENRY infant feeding group at Walthamstow Library',
    address: 'Walthamstow Library, High Street, London E17 7JN',
    postcode: 'E17 7JN',
    lat: 51.584478,
    long: -0.021034,
    category: 'infant feeding support',
    start_time: '11:00',
    end_time: '12:30',
    time_window: 'morning',
    borough: 'Waltham Forest',
    days_of_week: ['Wednesday'],
    website: 'https://www.walthamforest.gov.uk/events/henry-infant-feeding-group-drop-walthamstow-library',
    google_link:
      'https://www.google.com/maps/search/?api=1&query=Walthamstow%20Library%20High%20Street%20London%20E17%207JN',
    child_friendly_score: 4.6,
    app_rating: 4.4,
    number_of_reviews: 11,
    age_suitability: 'Parents feeding babies',
    description: 'Infant feeding support for breast, bottle, and mixed feeding.',
    cost: 'Free',
    followerNames: ['Noor'],
  },
  {
    activity_id: 'sample-7',
    activity_name: 'Stay and Play at Walthamstow Library',
    address: 'Walthamstow Library, High Street, London E17 7JN',
    postcode: 'E17 7JN',
    lat: 51.584478,
    long: -0.021034,
    category: 'baby stay and play',
    start_time: '12:00',
    end_time: '13:00',
    time_window: 'afternoon',
    borough: 'Waltham Forest',
    days_of_week: ['Wednesday', 'Friday'],
    website: 'https://www.walthamforest.gov.uk/events/stay-and-play-walthamstow-library-afternoon-session',
    google_link:
      'https://www.google.com/maps/search/?api=1&query=Walthamstow%20Library%20High%20Street%20London%20E17%207JN',
    child_friendly_score: 4.5,
    app_rating: 4.6,
    number_of_reviews: 22,
    age_suitability: 'Under 5s',
    description: 'Afternoon library stay-and-play session in the children area.',
    cost: 'Free',
    followerNames: ['Izzie'],
  },
  {
    activity_id: 'sample-8',
    activity_name: 'Stay and play at Wood Street Library',
    address: 'Wood Street Library, 1 Troubridge Square, Walthamstow, London E17 3GN',
    postcode: 'E17 3GN',
    lat: 51.587133,
    long: -0.004202,
    category: 'baby stay and play',
    start_time: '11:00',
    end_time: '12:00',
    time_window: 'morning',
    borough: 'Waltham Forest',
    days_of_week: ['Tuesday', 'Thursday'],
    website: 'https://www.walthamforest.gov.uk/events/stay-and-play-wood-street-library',
    google_link:
      'https://www.google.com/maps/search/?api=1&query=Wood%20Street%20Library%201%20Troubridge%20Square%20Walthamstow%20E17%203GN',
    child_friendly_score: 4.3,
    app_rating: 4.5,
    number_of_reviews: 16,
    age_suitability: '0 to 3 years',
    description: 'Library stay-and-play session for babies and toddlers.',
    cost: 'Free',
    followerNames: [],
  },
  {
    activity_id: 'sample-9',
    activity_name: 'William Morris Gallery with garden cafe',
    address: 'William Morris Gallery, Lloyd Park, Forest Road, London E17 4PP',
    postcode: 'E17 4PP',
    lat: 51.5917,
    long: -0.0206,
    category: 'museum',
    start_time: '13:30',
    end_time: '15:00',
    time_window: 'afternoon',
    borough: 'Waltham Forest',
    days_of_week: ['Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    website: 'https://www.wmgallery.org.uk/',
    google_link:
      'https://www.google.com/maps/search/?api=1&query=William%20Morris%20Gallery%20Lloyd%20Park%20E17%204PP',
    child_friendly_score: 4.2,
    app_rating: 4.6,
    number_of_reviews: 31,
    age_suitability: 'All ages',
    description: 'A gentle museum-and-cafe afternoon with buggy-friendly park time nearby.',
    cost: 'Free entry',
    followerNames: ['Leah', 'Maya'],
  },
  {
    activity_id: 'sample-10',
    activity_name: 'Coffee and buggy walk at Lloyd Park',
    address: 'Lloyd Park, Forest Road, London E17 4PP',
    postcode: 'E17 4PP',
    lat: 51.5912,
    long: -0.0214,
    category: 'coffee',
    start_time: '15:00',
    end_time: '16:00',
    time_window: 'afternoon',
    borough: 'Waltham Forest',
    days_of_week: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    website: 'https://www.walthamforest.gov.uk/libraries-arts-parks-and-leisure/parks-and-open-spaces/lloyd-park',
    google_link:
      'https://www.google.com/maps/search/?api=1&query=Lloyd%20Park%20Forest%20Road%20London%20E17%204PP',
    child_friendly_score: 4.7,
    app_rating: 4.4,
    number_of_reviews: 24,
    age_suitability: 'All ages',
    description: 'A flexible coffee stop with pram-friendly green space.',
    cost: 'Paid cafe items',
    followerNames: ['Noor'],
  },
  {
    activity_id: 'sample-11',
    activity_name: 'Early dinner at a child-friendly cafe',
    address: 'Hoe Street, Walthamstow, London E17',
    postcode: 'E17',
    lat: 51.5841,
    long: -0.0192,
    category: 'lunch',
    start_time: '17:00',
    end_time: '18:15',
    time_window: 'evening',
    borough: 'Waltham Forest',
    days_of_week: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    website: '',
    google_link: 'https://www.google.com/maps/search/?api=1&query=child%20friendly%20cafe%20Hoe%20Street%20Walthamstow',
    child_friendly_score: 4.1,
    app_rating: 4.2,
    number_of_reviews: 8,
    age_suitability: 'All ages',
    description: 'A low-effort early tea option for the days when cooking feels illegal.',
    cost: 'Paid food and drink',
    followerNames: [],
  },
];

export const categories = [
  'coffee',
  'lunch',
  'museum',
  'baby stay and play',
  'baby sing along',
  'baby yoga',
  'sensory play',
  'outdoor play',
  'post-natal support',
  'infant feeding support',
];

export const boroughs = ['Waltham Forest', 'Hackney', 'Islington', 'Newham'];

export const sampleParents = [
  { user_id: 'maya', user_name: 'maya_naps', display_name: 'Maya', followers: 18, following: 12 },
  { user_id: 'noor', user_name: 'noor_and_ravi', display_name: 'Noor', followers: 32, following: 24 },
  { user_id: 'izzie', user_name: 'izzie_wanders', display_name: 'Izzie', followers: 9, following: 7 },
  { user_id: 'leah', user_name: 'leah_local', display_name: 'Leah', followers: 41, following: 36 },
];
